# IntexuraOS Cloud Build Configuration
# Builds and deploys affected services on push to development branch.
# CI checks (lint, typecheck, test) run in GitHub Actions before this.
#
# Substitutions are provided by the Cloud Build trigger (Terraform):
# - _REGION: GCP region
# - _ARTIFACT_REGISTRY_URL: Full Artifact Registry URL
# - _ENVIRONMENT: Environment name (dev, staging, prod)

steps:
  # Step 1: Install dependencies (needed for builds)
  - name: 'node:22-slim'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 2: Detect affected services (uses full node image for git)
  - name: 'node:22'
    id: 'detect-affected'
    waitFor: ['npm-ci']
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  # ===== auth-service pipeline =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-auth-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building auth-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/auth-service:latest \
            -f apps/auth-service/Dockerfile .
        else
          echo "auth-service not affected, skipping build."
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-auth-service'
    waitFor: ['build-auth-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing auth-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:latest
        else
          echo "auth-service not affected, skipping push."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-auth-service'
    waitFor: ['push-auth-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-auth-service.sh
        else
          echo "auth-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== promptvault-service pipeline =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-promptvault-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building promptvault-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/promptvault-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest \
            -f apps/promptvault-service/Dockerfile .
        else
          echo "promptvault-service not affected, skipping build."
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-promptvault-service'
    waitFor: ['build-promptvault-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing promptvault-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/promptvault-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest
        else
          echo "promptvault-service not affected, skipping push."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-promptvault-service'
    waitFor: ['push-promptvault-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-promptvault-service.sh
        else
          echo "promptvault-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== notion-service pipeline =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-notion-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"notion-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building notion-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/notion-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/notion-service:latest \
            -f apps/notion-service/Dockerfile .
        else
          echo "notion-service not affected, skipping build."
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-notion-service'
    waitFor: ['build-notion-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"notion-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing notion-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-service:latest
        else
          echo "notion-service not affected, skipping push."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-notion-service'
    waitFor: ['push-notion-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"notion-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-notion-service.sh
        else
          echo "notion-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== whatsapp-service pipeline =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-whatsapp-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building whatsapp-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest \
            -f apps/whatsapp-service/Dockerfile .
        else
          echo "whatsapp-service not affected, skipping build."
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-whatsapp-service'
    waitFor: ['build-whatsapp-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing whatsapp-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest
        else
          echo "whatsapp-service not affected, skipping push."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-whatsapp-service'
    waitFor: ['push-whatsapp-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-whatsapp-service.sh
        else
          echo "whatsapp-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'


  # ===== api-docs-hub pipeline =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-docs-hub'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          echo "Building api-docs-hub..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest \
            -f apps/api-docs-hub/Dockerfile .
        else
          echo "api-docs-hub not affected, skipping build."
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-docs-hub'
    waitFor: ['build-api-docs-hub']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing api-docs-hub..."
          docker push ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest
        else
          echo "api-docs-hub not affected, skipping push."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api-docs-hub'
    waitFor: ['push-api-docs-hub']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-api-docs-hub.sh
        else
          echo "api-docs-hub not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== web pipeline =====
  # Step 1: Fetch secrets and write to .env file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'fetch-web-secrets'
    waitFor: ['npm-ci', 'detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "Fetching secrets for web build..."
          cat > /workspace/apps/web/.env << EOF
        INTEXURAOS_AUTH0_DOMAIN=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_DOMAIN)
        INTEXURAOS_AUTH0_SPA_CLIENT_ID=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_SPA_CLIENT_ID)
        INTEXURAOS_AUTH_AUDIENCE=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_AUDIENCE)
        INTEXURAOS_AUTH_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_SERVICE_URL)
        INTEXURAOS_PROMPTVAULT_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_PROMPTVAULT_SERVICE_URL)
        INTEXURAOS_WHATSAPP_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_WHATSAPP_SERVICE_URL)
        INTEXURAOS_NOTION_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_NOTION_SERVICE_URL)
        INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL)
        EOF
          echo "Secrets written to /workspace/apps/web/.env"
        else
          echo "web not affected, skipping secret fetch."
        fi

  # Step 2: Build web app with Node (reads .env file via Vite)
  - name: 'node:22-slim'
    id: 'build-web'
    waitFor: ['fetch-web-secrets']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "Building web app..."
          npm run --workspace=@intexuraos/web build
          echo "Web app build complete."
        else
          echo "web not affected, skipping build."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-web'
    waitFor: ['build-web']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-web.sh
        else
          echo "web not affected, skipping deploy."
        fi
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'

  # ===== static assets sync =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'sync-static-assets'
    waitFor: ['npm-ci']
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-static-assets.sh']
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'

# No substitutions block here - all substitutions come from the Terraform-managed
# Cloud Build trigger. This ensures single source of truth.

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s
