# IntexuraOS Cloud Build Configuration
# Builds and deploys affected services on push to development branch.
# CI checks (lint, typecheck, test) run in GitHub Actions before this.
#
# Optimizations applied:
# - Docker BuildKit with layer caching (--cache-from)
# - Parallel builds for all services (waitFor: ['detect-affected'])
# - Single detection pass (affected.json written once)
# - CLOUD_LOGGING_ONLY for cost savings
#
# Substitutions are provided by the Cloud Build trigger (Terraform):
# - _REGION: GCP region
# - _ARTIFACT_REGISTRY_URL: Full Artifact Registry URL
# - _ENVIRONMENT: Environment name (dev, staging, prod)

steps:
  # Step 1: Install dependencies (needed for web build)
  - name: 'node:22-slim'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 2: Detect affected services (single pass - result in /workspace/affected.json)
  - name: 'node:22'
    id: 'detect-affected'
    waitFor: ['npm-ci']
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  # ===== PARALLEL SERVICE PIPELINES =====
  # All build steps wait only for detect-affected, enabling parallel execution
  # Build+Push use gcr.io/cloud-builders/docker, Deploy uses cloud-sdk

  # ===== auth-service =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push-auth-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building auth-service ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/auth-service:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/auth-service:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/auth-service:latest \
            -f apps/auth-service/Dockerfile .
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:latest
        else
          echo "auth-service not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-auth-service'
    waitFor: ['build-push-auth-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-auth-service.sh
        else
          echo "auth-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== promptvault-service =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push-promptvault-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building promptvault-service ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/promptvault-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest \
            -f apps/promptvault-service/Dockerfile .
          docker push ${_ARTIFACT_REGISTRY_URL}/promptvault-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest
        else
          echo "promptvault-service not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-promptvault-service'
    waitFor: ['build-push-promptvault-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-promptvault-service.sh
        else
          echo "promptvault-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== notion-service =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push-notion-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"notion-service"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building notion-service ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/notion-service:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/notion-service:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/notion-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/notion-service:latest \
            -f apps/notion-service/Dockerfile .
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-service:latest
        else
          echo "notion-service not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-notion-service'
    waitFor: ['build-push-notion-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"notion-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-notion-service.sh
        else
          echo "notion-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== whatsapp-service =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push-whatsapp-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building whatsapp-service ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest \
            -f apps/whatsapp-service/Dockerfile .
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest
        else
          echo "whatsapp-service not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-whatsapp-service'
    waitFor: ['build-push-whatsapp-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-whatsapp-service.sh
        else
          echo "whatsapp-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== api-docs-hub =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push-api-docs-hub'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building api-docs-hub ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest \
            -f apps/api-docs-hub/Dockerfile .
          docker push ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest
        else
          echo "api-docs-hub not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api-docs-hub'
    waitFor: ['build-push-api-docs-hub']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-api-docs-hub.sh
        else
          echo "api-docs-hub not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== mobile-notifications-service =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push-mobile-notifications-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"mobile-notifications-service"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building mobile-notifications-service ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/mobile-notifications-service:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/mobile-notifications-service:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/mobile-notifications-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/mobile-notifications-service:latest \
            -f apps/mobile-notifications-service/Dockerfile .
          docker push ${_ARTIFACT_REGISTRY_URL}/mobile-notifications-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/mobile-notifications-service:latest
        else
          echo "mobile-notifications-service not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-mobile-notifications-service'
    waitFor: ['build-push-mobile-notifications-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"mobile-notifications-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-mobile-notifications-service.sh
        else
          echo "mobile-notifications-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== web (static frontend) =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'web'
    waitFor: ['npm-ci', 'detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "=== Fetching secrets for web ==="
          cat > /workspace/apps/web/.env << EOF
        INTEXURAOS_AUTH0_DOMAIN=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_DOMAIN)
        INTEXURAOS_AUTH0_SPA_CLIENT_ID=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_SPA_CLIENT_ID)
        INTEXURAOS_AUTH_AUDIENCE=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_AUDIENCE)
        INTEXURAOS_AUTH_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_SERVICE_URL)
        INTEXURAOS_PROMPTVAULT_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_PROMPTVAULT_SERVICE_URL)
        INTEXURAOS_WHATSAPP_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_WHATSAPP_SERVICE_URL)
        INTEXURAOS_NOTION_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_NOTION_SERVICE_URL)
        INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL)
        EOF

          echo "=== Building web ==="
          npm run --workspace=@intexuraos/web build

          echo "=== Deploying web ==="
          bash cloudbuild/scripts/deploy-web.sh
        else
          echo "web not affected, skipping."
        fi
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'

  # ===== static assets sync =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'static-assets'
    waitFor: ['npm-ci']
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-static-assets.sh']
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  env:
    - 'DOCKER_BUILDKIT=1'

timeout: 1800s

