# Manual trigger: Deploy Firestore migrations only
steps:
  - name: 'node:22-slim'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm@9
        pnpm install --frozen-lockfile
        bash cloudbuild/scripts/deploy-firestore.sh
    env:
      - 'PROJECT_ID=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: '600s'
