# IntexuraOS Cloud Build Configuration
# Builds and deploys affected services on push to development branch.
# CI checks (lint, typecheck, test) run in GitHub Actions before this.
#
# Optimizations applied:
# - Docker BuildKit with layer caching (--cache-from)
# - Parallel builds for all services (waitFor: ['detect-affected'])
# - Combined build-push-deploy in single step per service
# - Single detection pass (affected.json written once)
# - CLOUD_LOGGING_ONLY for cost savings
#
# Substitutions are provided by the Cloud Build trigger (Terraform):
# - _REGION: GCP region
# - _ARTIFACT_REGISTRY_URL: Full Artifact Registry URL
# - _ENVIRONMENT: Environment name (dev, staging, prod)

steps:
  # Step 1: Install dependencies (needed for web build)
  - name: 'node:22-slim'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 2: Detect affected services (single pass - result in /workspace/affected.json)
  - name: 'node:22'
    id: 'detect-affected'
    waitFor: ['npm-ci']
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  # ===== PARALLEL SERVICE PIPELINES =====
  # All steps wait only for detect-affected, enabling parallel execution
  # Each step: build → push → deploy in single container

  # ===== auth-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'auth-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE="auth-service"
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q "\"$$SERVICE\"" /workspace/affected.json 2>/dev/null; then
          echo "=== Building $$SERVICE ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            -f apps/$$SERVICE/Dockerfile .

          echo "=== Pushing $$SERVICE ==="
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest

          echo "=== Deploying $$SERVICE ==="
          bash cloudbuild/scripts/deploy-$$SERVICE.sh
        else
          echo "$$SERVICE not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== promptvault-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'promptvault-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE="promptvault-service"
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q "\"$$SERVICE\"" /workspace/affected.json 2>/dev/null; then
          echo "=== Building $$SERVICE ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            -f apps/$$SERVICE/Dockerfile .

          echo "=== Pushing $$SERVICE ==="
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest

          echo "=== Deploying $$SERVICE ==="
          bash cloudbuild/scripts/deploy-$$SERVICE.sh
        else
          echo "$$SERVICE not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== notion-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'notion-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE="notion-service"
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q "\"$$SERVICE\"" /workspace/affected.json 2>/dev/null; then
          echo "=== Building $$SERVICE ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            -f apps/$$SERVICE/Dockerfile .

          echo "=== Pushing $$SERVICE ==="
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest

          echo "=== Deploying $$SERVICE ==="
          bash cloudbuild/scripts/deploy-$$SERVICE.sh
        else
          echo "$$SERVICE not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== whatsapp-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'whatsapp-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE="whatsapp-service"
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q "\"$$SERVICE\"" /workspace/affected.json 2>/dev/null; then
          echo "=== Building $$SERVICE ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            -f apps/$$SERVICE/Dockerfile .

          echo "=== Pushing $$SERVICE ==="
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest

          echo "=== Deploying $$SERVICE ==="
          bash cloudbuild/scripts/deploy-$$SERVICE.sh
        else
          echo "$$SERVICE not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== api-docs-hub =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'api-docs-hub'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE="api-docs-hub"
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q "\"$$SERVICE\"" /workspace/affected.json 2>/dev/null; then
          echo "=== Building $$SERVICE ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            -f apps/$$SERVICE/Dockerfile .

          echo "=== Pushing $$SERVICE ==="
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest

          echo "=== Deploying $$SERVICE ==="
          bash cloudbuild/scripts/deploy-$$SERVICE.sh
        else
          echo "$$SERVICE not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== mobile-notifications-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'mobile-notifications-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE="mobile-notifications-service"
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q "\"$$SERVICE\"" /workspace/affected.json 2>/dev/null; then
          echo "=== Building $$SERVICE ==="
          docker pull ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest || true
          docker build \
            --cache-from=${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest \
            -f apps/$$SERVICE/Dockerfile .

          echo "=== Pushing $$SERVICE ==="
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:$$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/$$SERVICE:latest

          echo "=== Deploying $$SERVICE ==="
          bash cloudbuild/scripts/deploy-$$SERVICE.sh
        else
          echo "$$SERVICE not affected, skipping."
        fi
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # ===== web (static frontend) =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'web'
    waitFor: ['npm-ci', 'detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "=== Fetching secrets for web ==="
          cat > /workspace/apps/web/.env << EOF
        INTEXURAOS_AUTH0_DOMAIN=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_DOMAIN)
        INTEXURAOS_AUTH0_SPA_CLIENT_ID=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_SPA_CLIENT_ID)
        INTEXURAOS_AUTH_AUDIENCE=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_AUDIENCE)
        INTEXURAOS_AUTH_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_SERVICE_URL)
        INTEXURAOS_PROMPTVAULT_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_PROMPTVAULT_SERVICE_URL)
        INTEXURAOS_WHATSAPP_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_WHATSAPP_SERVICE_URL)
        INTEXURAOS_NOTION_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_NOTION_SERVICE_URL)
        INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL)
        EOF

          echo "=== Building web ==="
          npm run --workspace=@intexuraos/web build

          echo "=== Deploying web ==="
          bash cloudbuild/scripts/deploy-web.sh
        else
          echo "web not affected, skipping."
        fi
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'

  # ===== static assets sync (parallel with everything) =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'static-assets'
    waitFor: ['npm-ci']
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-static-assets.sh']
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'

# No substitutions block here - all substitutions come from the Terraform-managed
# Cloud Build trigger. This ensures single source of truth.

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  env:
    - 'DOCKER_BUILDKIT=1'

timeout: 1800s

