# IntexuraOS Hyper-Fast Orchestrator
steps:
  # 1. Analyze & Generate Plan (Runs in ~5-10 seconds)
  # Uses alpine to keep image pull fast. Installs git for diffing.
  - name: 'node:22-alpine'
    id: 'plan'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache git
        node cloudbuild/scripts/orchestrate.mjs
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'PROJECT_ID=$PROJECT_ID'
      - '_REGION=${_REGION}'
      - '_ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - '_ENVIRONMENT=${_ENVIRONMENT}'
      - '_FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # 2. Execute the Plan (0 startup time if skipped)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'execute'
    waitFor: ['plan']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -f cloudbuild.dynamic.json ]; then
          echo "No services affected. Skipping build."
          exit 0
        fi

        echo ">> Submitting child build..."
        # Submit the dynamic config.
        # CRITICAL: This respects .gcloudignore to avoid uploading node_modules
        gcloud builds submit . \
          --config=cloudbuild.dynamic.json \
          --project=$PROJECT_ID \
          --region=${_REGION} \
          --substitutions=_REGION=${_REGION},_ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL},_ENVIRONMENT=${_ENVIRONMENT}

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
