# PraxOS Cloud Build Configuration
# Builds and deploys affected services on push to development branch.
#
# Substitutions are provided by the Cloud Build trigger (Terraform):
# - _REGION: GCP region
# - _ARTIFACT_REGISTRY_URL: Full Artifact Registry URL
# - _ENVIRONMENT: Environment name (dev, staging, prod)

steps:
  # Step 1: Show Node.js version
  - name: 'node:22-slim'
    id: 'node-version'
    entrypoint: 'node'
    args: ['--version']

  # Step 2: Install dependencies
  - name: 'node:22-slim'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 3: Run CI checks (lint, typecheck, test, build)
  - name: 'node:22-slim'
    id: 'npm-run-ci'
    entrypoint: 'npm'
    args: ['run', 'ci']

  # Step 4: Detect affected services
  - name: 'node:22-slim'
    id: 'detect-affected'
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  # Step 5: Build auth-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-auth-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building auth-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/auth-service:latest \
            -f apps/auth-service/Dockerfile .
        else
          echo "auth-service not affected, skipping build."
        fi

  # Step 6: Build notion-gpt-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-notion-gpt-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"notion-gpt-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building notion-gpt-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:latest \
            -f apps/notion-gpt-service/Dockerfile .
        else
          echo "notion-gpt-service not affected, skipping build."
        fi

  # Step 7: Build whatsapp-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-whatsapp-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building whatsapp-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest \
            -f apps/whatsapp-service/Dockerfile .
        else
          echo "whatsapp-service not affected, skipping build."
        fi

  # Step 8: Push auth-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-auth-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing auth-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:latest
        else
          echo "auth-service not affected, skipping push."
        fi

  # Step 9: Push notion-gpt-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-notion-gpt-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"notion-gpt-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing notion-gpt-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:latest
        else
          echo "notion-gpt-service not affected, skipping push."
        fi

  # Step 10: Push whatsapp-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-whatsapp-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing whatsapp-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest
        else
          echo "whatsapp-service not affected, skipping push."
        fi

  # Step 11: Deploy affected services to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-affected'
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-affected.sh']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

# No substitutions block here - all substitutions come from the Terraform-managed
# Cloud Build trigger. This ensures single source of truth.

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s
