# IntexuraOS Cloud Build Configuration
# Deploys services using pre-built images from Artifact Registry.
# Docker images are built in GitHub Actions for cost efficiency.
# Web frontend is built here (needs Secret Manager access).
#
# Substitutions are provided by the Cloud Build trigger (Terraform):
# - _REGION: GCP region
# - _ARTIFACT_REGISTRY_URL: Full Artifact Registry URL
# - _ENVIRONMENT: Environment name (dev, staging, prod)

steps:
  # Step 1: Install dependencies (needed for web build and affected detection)
  - name: 'node:22-slim'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 2: Detect affected services (single pass - result in /workspace/affected.json)
  # Compares with last SUCCESSFUL build to avoid skipping changes from failed builds
  - name: 'node:22'
    id: 'detect-affected'
    waitFor: ['npm-ci']
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REGION=${_REGION}'

  # ===== SERVICE DEPLOYS (images pre-built in GitHub Actions) =====
  # All deploy steps run in parallel, waiting only for detect-affected

  # ===== user-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-user-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"user-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-user-service.sh
        else
          echo "user-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== promptvault-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-promptvault-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-promptvault-service.sh
        else
          echo "promptvault-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== notion-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-notion-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"notion-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-notion-service.sh
        else
          echo "notion-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== whatsapp-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-whatsapp-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-whatsapp-service.sh
        else
          echo "whatsapp-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== api-docs-hub =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api-docs-hub'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-api-docs-hub.sh
        else
          echo "api-docs-hub not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== mobile-notifications-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-mobile-notifications-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"mobile-notifications-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-mobile-notifications-service.sh
        else
          echo "mobile-notifications-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== llm-orchestrator-service =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-llm-orchestrator-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"llm-orchestrator-service"' /workspace/affected.json 2>/dev/null; then
          bash cloudbuild/scripts/deploy-llm-orchestrator-service.sh
        else
          echo "llm-orchestrator-service not affected, skipping deploy."
        fi
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

  # ===== web (static frontend - built in Cloud Build for Secret Manager access) =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'fetch-web-secrets'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "=== Fetching secrets for web ==="
          cat > /workspace/apps/web/.env << EOF
        INTEXURAOS_AUTH0_DOMAIN=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_DOMAIN)
        INTEXURAOS_AUTH0_SPA_CLIENT_ID=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH0_SPA_CLIENT_ID)
        INTEXURAOS_AUTH_AUDIENCE=$(gcloud secrets versions access latest --secret=INTEXURAOS_AUTH_AUDIENCE)
        INTEXURAOS_USER_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_USER_SERVICE_URL)
        INTEXURAOS_PROMPTVAULT_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_PROMPTVAULT_SERVICE_URL)
        INTEXURAOS_WHATSAPP_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_WHATSAPP_SERVICE_URL)
        INTEXURAOS_NOTION_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_NOTION_SERVICE_URL)
        INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL)
        INTEXURAOS_LLM_ORCHESTRATOR_SERVICE_URL=$(gcloud secrets versions access latest --secret=INTEXURAOS_LLM_ORCHESTRATOR_SERVICE_URL)
        EOF
          echo "Secrets written to /workspace/apps/web/.env"
        else
          echo "web not affected, skipping secret fetch."
        fi

  - name: 'node:22-slim'
    id: 'build-web'
    waitFor: ['npm-ci', 'fetch-web-secrets']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "=== Building web ==="
          npm run --workspace=@intexuraos/web build
        else
          echo "web not affected, skipping build."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-web'
    waitFor: ['build-web']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_FORCE_DEPLOY}" == "true" ]] || grep -q '"web"' /workspace/affected.json 2>/dev/null; then
          echo "=== Deploying web ==="
          bash cloudbuild/scripts/deploy-web.sh
        else
          echo "web not affected, skipping deploy."
        fi
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'

  # ===== static assets sync =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'static-assets'
    waitFor: ['npm-ci']
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-static-assets.sh']
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

timeout: 900s
