# PraxOS Cloud Build Configuration
# Builds and deploys affected services on push to development branch.
#
# Substitutions are provided by the Cloud Build trigger (Terraform):
# - _REGION: GCP region
# - _ARTIFACT_REGISTRY_URL: Full Artifact Registry URL
# - _ENVIRONMENT: Environment name (dev, staging, prod)

steps:
  # Step 1: Show Node.js version
  - name: 'node:22-slim'
    id: 'node-version'
    entrypoint: 'node'
    args: ['--version']

  # Step 2: Install dependencies
  - name: 'node:22-slim'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 3: Start Firestore emulator (background sidecar for tests)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'start-firestore-emulator'
    waitFor: ['npm-ci']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run -d --name firestore-emulator \
          --network cloudbuild \
          google/cloud-sdk:emulators \
          gcloud emulators firestore start --host-port=0.0.0.0:8085 --project=test-project
        # Wait for emulator to be ready
        echo "Waiting for Firestore emulator to start..."
        for i in {1..30}; do
          if docker exec firestore-emulator curl -sf http://localhost:8085/ > /dev/null 2>&1; then
            echo "Firestore emulator is ready."
            exit 0
          fi
          sleep 1
        done
        echo "Firestore emulator failed to start within 30s"
        docker logs firestore-emulator
        exit 1

  # Step 4: Run CI checks (lint, typecheck, test, build)
  - name: 'node:22-slim'
    id: 'npm-run-ci'
    waitFor: ['start-firestore-emulator']
    entrypoint: 'npm'
    args: ['run', 'ci']
    env:
      - 'FIRESTORE_EMULATOR_HOST=firestore-emulator:8085'
      - 'GCLOUD_PROJECT=test-project'

  # Step 5: Detect affected services (uses full node image for git)
  - name: 'node:22'
    id: 'detect-affected'
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  # Step 6: Build auth-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-auth-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building auth-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/auth-service:latest \
            -f apps/auth-service/Dockerfile .
        else
          echo "auth-service not affected, skipping build."
        fi

  # Step 7: Build promptvault-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-promptvault-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building promptvault-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/promptvault-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest \
            -f apps/promptvault-service/Dockerfile .
        else
          echo "promptvault-service not affected, skipping build."
        fi

  # Step 8: Build whatsapp-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-whatsapp-service'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building whatsapp-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest \
            -f apps/whatsapp-service/Dockerfile .
        else
          echo "whatsapp-service not affected, skipping build."
        fi

  # Step 9: Build api-docs-hub Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-docs-hub'
    waitFor: ['detect-affected']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          echo "Building api-docs-hub..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest \
            -f apps/api-docs-hub/Dockerfile .
        else
          echo "api-docs-hub not affected, skipping build."
        fi

  # Step 10: Push auth-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-auth-service'
    waitFor: ['build-auth-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing auth-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:latest
        else
          echo "auth-service not affected, skipping push."
        fi

  # Step 11: Push promptvault-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-promptvault-service'
    waitFor: ['build-promptvault-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"promptvault-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing promptvault-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/promptvault-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/promptvault-service:latest
        else
          echo "promptvault-service not affected, skipping push."
        fi

  # Step 12: Push whatsapp-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-whatsapp-service'
    waitFor: ['build-whatsapp-service']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"whatsapp-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing whatsapp-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/whatsapp-service:latest
        else
          echo "whatsapp-service not affected, skipping push."
        fi

  # Step 13: Push api-docs-hub image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-docs-hub'
    waitFor: ['build-api-docs-hub']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"api-docs-hub"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing api-docs-hub..."
          docker push ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/api-docs-hub:latest
        else
          echo "api-docs-hub not affected, skipping push."
        fi

  # Step 14: Deploy affected services to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-affected'
    waitFor:
      [
        'push-auth-service',
        'push-promptvault-service',
        'push-whatsapp-service',
        'push-api-docs-hub',
      ]
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-affected.sh']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'FORCE_DEPLOY=${_FORCE_DEPLOY}'

  # Step 15: Sync static assets to GCS bucket (runs in parallel with deploys)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'sync-static-assets'
    waitFor: ['npm-run-ci']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Syncing static assets to GCS bucket..."
        BUCKET="praxos-static-assets-${_ENVIRONMENT}"
        echo "Bucket name: $$BUCKET"
        echo "Syncing docs/assets/** to gs://$$BUCKET/"
        gsutil -m rsync -r -d docs/assets/ "gs://$$BUCKET/"
        echo "Static assets sync complete."

# No substitutions block here - all substitutions come from the Terraform-managed
# Cloud Build trigger. This ensures single source of truth.

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s
