# PraxOS Cloud Build Configuration
# Builds and deploys affected services on push to development branch.

steps:
  # Step 1: Show Node.js version
  - name: 'node:20'
    id: 'node-version'
    entrypoint: 'node'
    args: ['--version']

  # Step 2: Install dependencies
  - name: 'node:20'
    id: 'npm-ci'
    entrypoint: 'npm'
    args: ['ci']

  # Step 3: Run CI checks (lint, typecheck, test, build)
  - name: 'node:20'
    id: 'npm-run-ci'
    entrypoint: 'npm'
    args: ['run', 'ci']

  # Step 4: Detect affected services
  - name: 'node:20'
    id: 'detect-affected'
    entrypoint: 'node'
    args: ['cloudbuild/scripts/detect-affected.mjs']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  # Step 5: Build auth-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-auth-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building auth-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/auth-service:latest \
            -f apps/auth-service/Dockerfile .
        else
          echo "auth-service not affected, skipping build."
        fi

  # Step 6: Build notion-gpt-service Docker image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-notion-gpt-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"notion-gpt-service"' /workspace/affected.json 2>/dev/null; then
          echo "Building notion-gpt-service..."
          docker build -t ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:$COMMIT_SHA \
            -t ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:latest \
            -f apps/notion-gpt-service/Dockerfile .
        else
          echo "notion-gpt-service not affected, skipping build."
        fi

  # Step 7: Push auth-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-auth-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing auth-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/auth-service:latest
        else
          echo "auth-service not affected, skipping push."
        fi

  # Step 8: Push notion-gpt-service image (if affected)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-notion-gpt-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"notion-gpt-service"' /workspace/affected.json 2>/dev/null; then
          echo "Pushing notion-gpt-service..."
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:$COMMIT_SHA
          docker push ${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:latest
        else
          echo "notion-gpt-service not affected, skipping push."
        fi

  # Step 9: Deploy affected services to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-affected'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -q '"auth-service"' /workspace/affected.json 2>/dev/null; then
          echo "Deploying auth-service to Cloud Run..."
          gcloud run deploy praxos-auth-service \
            --image=${_ARTIFACT_REGISTRY_URL}/auth-service:$COMMIT_SHA \
            --region=${_REGION} \
            --platform=managed \
            --quiet
        fi

        if grep -q '"notion-gpt-service"' /workspace/affected.json 2>/dev/null; then
          echo "Deploying notion-gpt-service to Cloud Run..."
          gcloud run deploy praxos-notion-gpt-service \
            --image=${_ARTIFACT_REGISTRY_URL}/notion-gpt-service:$COMMIT_SHA \
            --region=${_REGION} \
            --platform=managed \
            --quiet
        fi

        echo "Deployment complete."

substitutions:
  _REGION: europe-central2
  _ARTIFACT_REGISTRY_URL: europe-central2-docker.pkg.dev/${PROJECT_ID}/praxos-dev
  _ENVIRONMENT: dev

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s
