# Manual trigger: Deploy web only
steps:
  - name: 'node:22-slim'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm run --workspace=@intexuraos/web build
    secretEnv:
      - 'INTEXURAOS_FIREBASE_API_KEY'
      - 'INTEXURAOS_FIREBASE_AUTH_DOMAIN'
      - 'INTEXURAOS_FIREBASE_PROJECT_ID'
      - 'INTEXURAOS_AUTH0_SPA_CLIENT_ID'
      - 'INTEXURAOS_AUTH0_DOMAIN'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-web.sh']
    env:
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - 'REGION=${_REGION}'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/INTEXURAOS_FIREBASE_API_KEY/versions/latest
      env: 'INTEXURAOS_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/INTEXURAOS_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'INTEXURAOS_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/INTEXURAOS_FIREBASE_PROJECT_ID/versions/latest
      env: 'INTEXURAOS_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/INTEXURAOS_AUTH0_SPA_CLIENT_ID/versions/latest
      env: 'INTEXURAOS_AUTH0_SPA_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/INTEXURAOS_AUTH0_DOMAIN/versions/latest
      env: 'INTEXURAOS_AUTH0_DOMAIN'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: '900s'

