/**
 * Research Routes
 *
 * POST   /research                  - Create new research
 * POST   /research/draft            - Save research as draft
 * GET    /research                  - List user's researches
 * GET    /research/:id              - Get single research
 * POST   /research/:id/approve      - Approve draft research
 * POST   /research/:id/confirm      - Confirm partial failure decision
 * POST   /research/:id/retry        - Retry from failed status
 * POST   /research/:id/enhance      - Create enhanced research from completed
 * POST   /research/:id/export-notion - Manually export to Notion
 * DELETE /research/:id              - Delete research
 * DELETE /research/:id/share        - Remove public share access
 * PATCH  /research/:id/favourite    - Toggle favourite status
 */

import type { FastifyPluginCallback, FastifyReply, FastifyRequest } from 'fastify';
import { logIncomingRequest, requireAuth, type AuthUser } from '@intexuraos/common-http';
import type { Logger } from 'pino';
import {
  createDraftResearch,
  createLlmResults,
  deleteResearch,
  enhanceResearch,
  type InputContext,
  getResearch,
  listResearches,
  type PartialFailureDecision,
  type Research,
  type ResearchModel,
  retryFailedLlms,
  retryFromFailed,
  runSynthesis,
  submitResearch,
  toggleResearchFavourite,
  unshareResearch,
  generateContextLabels,
  type GeneratedByUserInfo,
} from '../domain/research/index.js';
import {
  DEFAULT_PLATFORM_LLM_MODEL,
  DEFAULT_RESEARCH_SYNTHESIS_MODEL,
} from '@intexuraos/llm-contract';
import { getServices } from '../services.js';
import { createSynthesisProviders } from './helpers/synthesisHelper.js';
import {
  getUnsupportedHistoricalModels,
  getUnsupportedRetryMessage,
  getUnsupportedSynthesisMessage,
  isExecutableSynthesisModel,
} from './helpers/storedResearchModels.js';
import {
  approveResearchResponseSchema,
  confirmPartialFailureBodySchema,
  confirmPartialFailureResponseSchema,
  createResearchBodySchema,
  createResearchResponseSchema,
  deleteResearchResponseSchema,
  enhanceResearchBodySchema,
  enhanceResearchResponseSchema,
  exportNotionResponseSchema,
  getResearchResponseSchema,
  listResearchesQuerySchema,
  listResearchesResponseSchema,
  researchIdParamsSchema,
  retryFromFailedResponseSchema,
  saveDraftBodySchema,
  saveDraftResponseSchema,
  toggleFavouriteBodySchema,
  toggleFavouriteResponseSchema,
  updateDraftBodySchema,
  validateInputBodySchema,
  validateInputResponseSchema,
  improveInputBodySchema,
  improveInputResponseSchema,
} from './schemas/index.js';

interface CreateResearchBody {
  prompt: string;
  originalPrompt?: string;
  selectedModels: ResearchModel[];
  synthesisModel?: ResearchModel;
  inputContexts?: { content: string; label?: string }[];
  skipSynthesis?: boolean;
}

interface SaveDraftBody {
  prompt: string;
  selectedModels?: ResearchModel[];
  synthesisModel?: ResearchModel;
  inputContexts?: { content: string; label?: string }[];
}

interface ListResearchesQuery {
  limit?: number;
  cursor?: string;
}

interface ResearchIdParams {
  id: string;
}

interface ConfirmPartialFailureBody {
  action: PartialFailureDecision;
}

interface EnhanceResearchBody {
  additionalModels?: ResearchModel[];
  additionalContexts?: { content: string; label?: string }[];
  synthesisModel?: ResearchModel;
  removeContextIds?: string[];
}

function extractGeneratedByInfo(user: AuthUser, logger: Logger): GeneratedByUserInfo | undefined {
  // Auth0 Actions add claims under a custom namespace for API audiences
  // Try namespaced claims first, fall back to bare claims for ID tokens
  const NAMESPACE = 'https://intexuraos.cloud/';

  const namespacedNameKey = `${NAMESPACE}name`;
  const namespacedEmailKey = `${NAMESPACE}email`;

  /* v8 ignore start -- source-map: ternary type guards have source map alignment issues @preserve */
  const name =
    (typeof user.claims[namespacedNameKey] === 'string' ? user.claims[namespacedNameKey] : undefined) ??
    (typeof user.claims['name'] === 'string' ? user.claims['name'] : undefined);

  const email =
    (typeof user.claims[namespacedEmailKey] === 'string' ? user.claims[namespacedEmailKey] : undefined) ??
    (typeof user.claims['email'] === 'string' ? user.claims['email'] : undefined);
  /* v8 ignore stop @preserve */

  if (name === undefined && email === undefined) {
    logger.warn({ userId: user.userId }, 'Auth0 token missing name and email claims for "Generated by" attribution');
    return undefined;
  }

  const info: GeneratedByUserInfo = {};
  if (name !== undefined) {
    info.name = name;
  }
  if (email !== undefined) {
    info.email = email;
  }
  logger.info({ userId: user.userId, hasName: name !== undefined, hasEmail: email !== undefined }, 'Extracted author info from Auth0 claims');
  return info;
}

export const researchRoutes: FastifyPluginCallback = (fastify, _opts, done) => {
  // POST /research
  fastify.post(
    '/',
    {
      schema: {
        operationId: 'createResearch',
        summary: 'Create new research',
        description: 'Submit a research prompt to be processed by multiple LLMs.',
        tags: ['research'],
        body: createResearchBodySchema,
        response: {
          201: createResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'Received request to POST /research',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const body = request.body as CreateResearchBody;
      const {
        researchRepo,
        generateId,
        researchEventPublisher,
        userServiceClient,
        createTitleGenerator,
      } = getServices();

      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      if (!apiKeysResult.ok) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
      }
      const apiKeys = apiKeysResult.value;

      if (apiKeys.openrouter === undefined || apiKeys.openrouter === '') {
        return await reply.fail(
          'MISCONFIGURED',
          'OpenRouter API key is required for research'
        );
      }

      const synthesisModel = body.synthesisModel ?? DEFAULT_RESEARCH_SYNTHESIS_MODEL;

      const researchId = generateId();
      const submitParams: Parameters<typeof submitResearch>[0] = {
        userId: user.userId,
        prompt: body.prompt,
        selectedModels: body.selectedModels,
        synthesisModel,
      };
      if (body.originalPrompt !== undefined) {
        submitParams.originalPrompt = body.originalPrompt;
      }
      if (body.inputContexts !== undefined) {
        const contextsWithLabels = await generateContextLabels(
          body.inputContexts,
          apiKeys.openrouter,
          user.userId,
          createTitleGenerator,
          request.log,
          researchId
        );
        submitParams.inputContexts = contextsWithLabels;
      }
      if (body.skipSynthesis === true) {
        submitParams.skipSynthesis = true;
      }
      const generatedBy = extractGeneratedByInfo(user, request.log as Logger);
      if (generatedBy !== undefined) {
        if (generatedBy.name !== undefined) {
          submitParams.userName = generatedBy.name;
        }
        if (generatedBy.email !== undefined) {
          submitParams.userEmail = generatedBy.email;
        }
      }
      const result = await submitResearch(submitParams, {
        researchRepo,
        generateId: () => researchId,
        logger: request.log as unknown as Logger,
      });

      if (!result.ok) {
        return await reply.fail('INTERNAL_ERROR', result.error.message);
      }

      // Publish to Pub/Sub for async processing
      await researchEventPublisher.publishProcessResearch({
        type: 'research.process',
        researchId: result.value.id,
        userId: user.userId,
        triggeredBy: 'create',
      });

      return await reply.code(201).ok(result.value);
    }
  );

  // POST /research/draft
  fastify.post(
    '/draft',
    {
      schema: {
        operationId: 'saveDraft',
        summary: 'Save research as draft',
        description: 'Save a research draft with auto-generated title for later completion.',
        tags: ['research'],
        body: saveDraftBodySchema,
        response: {
          201: saveDraftResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/draft',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const body = request.body as SaveDraftBody;
      const { researchRepo, generateId, userServiceClient, createTitleGenerator } =
        getServices();
      const draftId = generateId();

      // Get user's API keys to generate title
      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      const apiKeys = apiKeysResult.ok ? apiKeysResult.value : {};

      // Generate title through the platform OpenRouter route when available.
      let title: string;
      if (apiKeys.openrouter !== undefined) {
        const titleGenerator = createTitleGenerator(
          DEFAULT_PLATFORM_LLM_MODEL,
          apiKeys.openrouter,
          user.userId,
          request.log,
          draftId
        );
        const titleResult = await titleGenerator.generateTitle(body.prompt);
        title = titleResult.ok ? titleResult.value.title : body.prompt.slice(0, 60);
      } else {
        // Fallback: use first 60 chars of prompt
        title = body.prompt.slice(0, 60);
      }

      // Create draft research (no default models - user must select before approving)
      const selectedModels = body.selectedModels ?? [];
      const draftParams: Parameters<typeof createDraftResearch>[0] = {
        id: draftId,
        userId: user.userId,
        title,
        prompt: body.prompt,
        selectedModels,
        synthesisModel: body.synthesisModel ?? DEFAULT_RESEARCH_SYNTHESIS_MODEL,
      };
      if (body.inputContexts !== undefined) {
        const contextsWithLabels = await generateContextLabels(
          body.inputContexts,
          apiKeys.openrouter,
          user.userId,
          createTitleGenerator,
          request.log,
          draftId
        );
        const now = new Date().toISOString();
        draftParams.inputContexts = contextsWithLabels.map((ctx) => {
          const inputContext: InputContext = {
            id: generateId(),
            content: ctx.content,
            addedAt: now,
          };
          /* v8 ignore start -- ts-type: ctx.label undefined-guard branch on save-draft route — exactOptionalPropertyTypes @preserve */
          if (ctx.label !== undefined) {
          /* v8 ignore stop @preserve */
            /* v8 ignore start -- ts-type: inputContext.label assignment after ctx.label undefined-guard — save-draft route @preserve */
            inputContext.label = ctx.label;
            /* v8 ignore stop @preserve */
          }
          return inputContext;
        });
      }
      const generatedBy = extractGeneratedByInfo(user, request.log as Logger);
      /* v8 ignore start -- ts-type: conditional object property assignment based on undefined check @preserve */
      if (generatedBy !== undefined) {
      /* v8 ignore stop @preserve */
        if (generatedBy.name !== undefined) {
          draftParams.userName = generatedBy.name;
        }
        if (generatedBy.email !== undefined) {
          draftParams.userEmail = generatedBy.email;
        }
      }
      const draft = createDraftResearch(draftParams);

      // Save draft
      const saveResult = await researchRepo.save(draft);
      if (!saveResult.ok) {
        return await reply.fail('INTERNAL_ERROR', saveResult.error.message);
      }

      return await reply.code(201).ok({ id: draft.id });
    }
  );

  // PATCH /research/:id
  fastify.patch(
    '/:id',
    {
      schema: {
        operationId: 'updateDraft',
        summary: 'Update draft research',
        description: 'Update an existing draft research. Only drafts can be updated.',
        tags: ['research'],
        params: researchIdParamsSchema,
        body: updateDraftBodySchema,
        response: {
          200: getResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'PATCH /research/:id',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const { id } = request.params as { id: string };
      const body = request.body as SaveDraftBody;
      const { researchRepo, generateId, userServiceClient, createTitleGenerator } =
        getServices();

      // Get existing research
      const existingResult = await researchRepo.findById(id);
      if (!existingResult.ok) {
        return await reply.fail('INTERNAL_ERROR', existingResult.error.message);
      }
      if (existingResult.value === null) {
        return await reply.fail('NOT_FOUND', 'Research not found');
      }

      const existing = existingResult.value;

      // Check ownership
      if (existing.userId !== user.userId) {
        return await reply.fail('FORBIDDEN', 'Not authorized to update this research');
      }

      // Can only update drafts
      if (existing.status !== 'draft') {
        return await reply.fail('CONFLICT', 'Can only update draft research');
      }

      // Get user's API keys to regenerate title if prompt changed
      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      const apiKeys = apiKeysResult.ok ? apiKeysResult.value : {};

      // Regenerate title if prompt changed
      let title = existing.title;
      if (body.prompt !== existing.prompt) {
        if (apiKeys.openrouter !== undefined) {
          const titleGenerator = createTitleGenerator(
            DEFAULT_PLATFORM_LLM_MODEL,
            apiKeys.openrouter,
            user.userId,
            request.log,
            id
          );
          const titleResult = await titleGenerator.generateTitle(body.prompt);
          title = titleResult.ok ? titleResult.value.title : body.prompt.slice(0, 60);
        } else {
          title = body.prompt.slice(0, 60);
        }
      }

      // Update draft
      const newSelectedModels = body.selectedModels ?? existing.selectedModels;
      const updates: Partial<Research> = {
        title,
        prompt: body.prompt,
        selectedModels: newSelectedModels,
        synthesisModel: body.synthesisModel ?? existing.synthesisModel,
        llmResults: createLlmResults(newSelectedModels),
      };

      if (body.inputContexts !== undefined) {
        const contextsWithLabels = await generateContextLabels(
          body.inputContexts,
          apiKeys.openrouter,
          user.userId,
          createTitleGenerator,
          request.log,
          id
        );
        const now = new Date().toISOString();
        updates.inputContexts = contextsWithLabels.map((ctx) => {
          const inputContext: InputContext = {
            id: generateId(),
            content: ctx.content,
            addedAt: now,
          };
          /* v8 ignore start -- ts-type: ctx.label undefined-guard branch on update-draft route — exactOptionalPropertyTypes @preserve */
          if (ctx.label !== undefined) {
          /* v8 ignore stop @preserve */
            /* v8 ignore start -- ts-type: inputContext.label assignment after ctx.label undefined-guard — update-draft route @preserve */
            inputContext.label = ctx.label;
            /* v8 ignore stop @preserve */
          }
          return inputContext;
        });
      }

      const updateResult = await researchRepo.update(id, updates);
      if (!updateResult.ok) {
        return await reply.fail('INTERNAL_ERROR', updateResult.error.message);
      }

      // Return updated research
      const updatedResult = await researchRepo.findById(id);
      if (!updatedResult.ok || updatedResult.value === null) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to retrieve updated research');
      }

      return await reply.ok(updatedResult.value);
    }
  );

  // POST /research/validate-input
  fastify.post(
    '/validate-input',
    {
      schema: {
        operationId: 'validateInput',
        summary: 'Validate research input quality',
        description:
          'Validates input quality and optionally returns improvement suggestion for weak prompts.',
        tags: ['research'],
        body: validateInputBodySchema,
        response: {
          200: validateInputResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/validate-input',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const body = request.body as { prompt: string; includeImprovement?: boolean };
      const { userServiceClient, createInputValidator, generateId } = getServices();
      const requestId = generateId();
      const startTime = Date.now();

      // Use the platform OpenRouter key exposed by the internal user client.
      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      if (!apiKeysResult.ok) {
        request.log.error({ requestId }, 'Failed to fetch API keys');
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
      }

      const openRouterKey = apiKeysResult.value.openrouter;
      if (openRouterKey === undefined) {
        request.log.error({ requestId }, 'OpenRouter API key not configured');
        return await reply.fail('MISCONFIGURED', 'OpenRouter API key required for validation');
      }

      const validator = createInputValidator(
        DEFAULT_PLATFORM_LLM_MODEL,
        openRouterKey,
        user.userId,
        request.log
      );

      // Validate
      const validationResult = await validator.validateInput(body.prompt);
      if (!validationResult.ok) {
        request.log.error(
          {
            requestId,
            errorCode: validationResult.error.code,
            errorMessage: validationResult.error.message,
          },
          'Validation failed'
        );
        return await reply.code(500).send({
          success: false,
          error: {
            code: validationResult.error.code,
            message: validationResult.error.message,
          },
          diagnostics: { requestId, durationMs: Date.now() - startTime },
        });
      }

      const { quality, reason } = validationResult.value;
      let improvedPrompt: string | null = null;

      // Get improvement if requested and quality is WEAK_BUT_VALID
      if (body.includeImprovement === true && quality === 1) {
        const improvementResult = await validator.improveInput(body.prompt);
        if (improvementResult.ok) {
          improvedPrompt = improvementResult.value.improvedPrompt;
        }
      }

      return await reply.code(200).send({
        success: true,
        data: { quality, reason, improvedPrompt },
        diagnostics: { requestId, durationMs: Date.now() - startTime },
      });
    }
  );

  // POST /research/improve-input
  fastify.post(
    '/improve-input',
    {
      schema: {
        operationId: 'improveInput',
        summary: 'Improve research input',
        description: 'Force-improves input regardless of quality.',
        tags: ['research'],
        body: improveInputBodySchema,
        response: {
          200: improveInputResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/improve-input',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const body = request.body as { prompt: string };
      const { userServiceClient, createInputValidator, generateId } = getServices();
      const requestId = generateId();
      const startTime = Date.now();

      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      if (!apiKeysResult.ok) {
        request.log.error({ requestId }, 'Failed to fetch API keys');
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
      }

      const openRouterKey = apiKeysResult.value.openrouter;
      if (openRouterKey === undefined) {
        request.log.error({ requestId }, 'OpenRouter API key not configured');
        return await reply.fail('MISCONFIGURED', 'OpenRouter API key required for improvement');
      }

      const validator = createInputValidator(
        DEFAULT_PLATFORM_LLM_MODEL,
        openRouterKey,
        user.userId,
        request.log
      );

      const result = await validator.improveInput(body.prompt);
      if (!result.ok) {
        request.log.warn(
          { requestId, errorCode: result.error.code, errorMessage: result.error.message },
          'Improvement failed, returning original prompt'
        );
        return await reply.code(200).send({
          success: true,
          data: { improvedPrompt: body.prompt },
          diagnostics: { requestId, durationMs: Date.now() - startTime },
        });
      }

      return await reply.code(200).send({
        success: true,
        data: { improvedPrompt: result.value.improvedPrompt },
        diagnostics: { requestId, durationMs: Date.now() - startTime },
      });
    }
  );

  // GET /research
  fastify.get(
    '/',
    {
      schema: {
        operationId: 'listResearches',
        summary: 'List researches',
        description: "Get a paginated list of the user's researches.",
        tags: ['research'],
        querystring: listResearchesQuerySchema,
        response: {
          200: listResearchesResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, { message: 'GET /research' });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const query = request.query as ListResearchesQuery;
      const { researchRepo } = getServices();

      const params: { userId: string; limit?: number; cursor?: string } = {
        userId: user.userId,
      };
      /* v8 ignore start -- ts-type: query.limit undefined-guard branch on list-researches route @preserve */
      if (query.limit !== undefined) {
      /* v8 ignore stop @preserve */
        /* v8 ignore start -- ts-type: params.limit assignment after query.limit undefined-guard — list-researches route @preserve */
        params.limit = query.limit;
        /* v8 ignore stop @preserve */
      }
      /* v8 ignore start -- ts-type: query.cursor undefined-guard branch on list-researches route @preserve */
      if (query.cursor !== undefined) {
      /* v8 ignore stop @preserve */
        /* v8 ignore start -- ts-type: params.cursor assignment after query.cursor undefined-guard — list-researches route @preserve */
        params.cursor = query.cursor;
        /* v8 ignore stop @preserve */
      }

      const result = await listResearches(params, { researchRepo });

      if (!result.ok) {
        return await reply.fail('INTERNAL_ERROR', result.error.message);
      }

      return await reply.ok(result.value);
    }
  );

  // GET /research/:id
  fastify.get(
    '/:id',
    {
      schema: {
        operationId: 'getResearch',
        summary: 'Get research',
        description: 'Get details of a specific research.',
        tags: ['research'],
        params: researchIdParamsSchema,
        response: {
          200: getResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, { message: 'GET /research/:id' });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const params = request.params as ResearchIdParams;
      const { researchRepo } = getServices();

      const result = await getResearch(params.id, { researchRepo });

      if (!result.ok) {
        return await reply.fail('INTERNAL_ERROR', result.error.message);
      }

      /* v8 ignore start -- upstream: prior check validated result.ok; null branch is not reachable when test always seeds document @preserve */
      if (result.value === null) {
      /* v8 ignore stop @preserve */
        return await reply.fail('NOT_FOUND', 'Research not found');
      }

      // Check ownership
      /* v8 ignore start -- upstream: prior check ensures value is not null; ownership mismatch not reachable without multi-user test setup @preserve */
      if (result.value.userId !== user.userId) {
      /* v8 ignore stop @preserve */
        return await reply.fail('FORBIDDEN', 'Access denied');
      }

      return await reply.ok(result.value); // @allow-result-access -- result.ok narrowed at line 746 (outside 15-line hook window due to inline null-and-ownership guards)
    }
  );

  // POST /research/:id/approve
  fastify.post(
    '/:id/approve',
    {
      schema: {
        operationId: 'approveResearch',
        summary: 'Approve draft research',
        description: 'Approve a draft research and start processing.',
        tags: ['research'],
        params: researchIdParamsSchema,
        response: {
          200: approveResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/:id/approve',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const params = request.params as ResearchIdParams;
      const { researchRepo, researchEventPublisher } = getServices();

      const existing = await getResearch(params.id, { researchRepo });

      if (!existing.ok) {
        return await reply.fail('INTERNAL_ERROR', existing.error.message);
      }

      if (existing.value === null) {
        return await reply.fail('NOT_FOUND', 'Research not found');
      }

      if (existing.value.userId !== user.userId) {
        return await reply.fail('FORBIDDEN', 'Access denied');
      }

      if (existing.value.status !== 'draft') {
        return await reply.fail('CONFLICT', 'Research is not in draft status');
      }

      const unsupportedModels = getUnsupportedHistoricalModels(existing.value.selectedModels);
      if (unsupportedModels.length > 0) {
        return await reply.fail('CONFLICT', getUnsupportedRetryMessage(unsupportedModels));
      }

      if (new Set(existing.value.selectedModels).size !== existing.value.selectedModels.length) {
        return await reply.fail('CONFLICT', 'Research contains duplicate model IDs');
      }

      if (existing.value.selectedModels.length > 6) {
        return await reply.fail('CONFLICT', 'Research cannot contain more than 6 models');
      }

      if (
        existing.value.skipSynthesis !== true &&
        !isExecutableSynthesisModel(existing.value.synthesisModel)
      ) {
        return await reply.fail(
          'CONFLICT',
          getUnsupportedSynthesisMessage(existing.value.synthesisModel)
        );
      }

      const { userServiceClient } = getServices();
      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      if (!apiKeysResult.ok) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
      }
      const apiKeys = apiKeysResult.value;

      if (
        existing.value.selectedModels.length > 0 &&
        (apiKeys.openrouter === undefined || apiKeys.openrouter === '')
      ) {
        return await reply.fail(
          'MISCONFIGURED',
          'OpenRouter API key is required for research'
        );
      }

      if (
        (apiKeys.openrouter === undefined || apiKeys.openrouter === '') &&
        existing.value.skipSynthesis !== true
      ) {
        return await reply.fail(
          'MISCONFIGURED',
          `API key required for synthesis with ${existing.value.synthesisModel}`
        );
      }

      // Require at least one source: either models or input contexts
      const hasModels = existing.value.selectedModels.length > 0;
      const hasContexts =
        existing.value.inputContexts !== undefined && existing.value.inputContexts.length > 0;
      if (!hasModels && !hasContexts) {
        return await reply.fail(
          'INVALID_REQUEST',
          'Select at least one model or provide input context before starting research'
        );
      }

      const updateResult = await researchRepo.update(params.id, { status: 'pending' });

      if (!updateResult.ok) {
        return await reply.fail('INTERNAL_ERROR', updateResult.error.message);
      }

      // Publish to Pub/Sub for async processing
      await researchEventPublisher.publishProcessResearch({
        type: 'research.process',
        researchId: params.id,
        userId: user.userId,
        triggeredBy: 'approve',
      });

      return await reply.ok(updateResult.value);
    }
  );

  // POST /research/:id/confirm
  fastify.post(
    '/:id/confirm',
    {
      schema: {
        operationId: 'confirmPartialFailure',
        summary: 'Confirm partial failure decision',
        description:
          'Submit user decision for handling partial LLM failures: proceed with successful results, retry failed providers, or cancel.',
        tags: ['research'],
        params: researchIdParamsSchema,
        body: confirmPartialFailureBodySchema,
        response: {
          200: confirmPartialFailureResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/:id/confirm',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const { id } = request.params as ResearchIdParams;
      const body = request.body as ConfirmPartialFailureBody;
      const {
        researchRepo,
        userServiceClient,
        imageServiceClient,
        notificationSender,
        llmCallPublisher,
        shareStorage,
        shareConfig,
        webAppUrl,
        notionServiceClient,
        researchExportSettings,
      } = getServices();

      const existing = await getResearch(id, { researchRepo });

      if (!existing.ok) {
        return await reply.fail('INTERNAL_ERROR', existing.error.message);
      }

      if (existing.value === null) {
        return await reply.fail('NOT_FOUND', 'Research not found');
      }

      if (existing.value.userId !== user.userId) {
        return await reply.fail('FORBIDDEN', 'Access denied');
      }

      if (existing.value.status !== 'awaiting_confirmation') {
        return await reply.fail('CONFLICT', 'Research is not awaiting confirmation');
      }

      const research = existing.value;

      if (research.partialFailure === undefined) {
        return await reply.fail('CONFLICT', 'No partial failure info found');
      }

      const partialFailure = research.partialFailure;

      switch (body.action) {
        case 'proceed': {
          const synthesisModel = research.synthesisModel;
          if (!isExecutableSynthesisModel(synthesisModel)) {
            return await reply.fail('CONFLICT', getUnsupportedSynthesisMessage(synthesisModel));
          }

          const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
          if (!apiKeysResult.ok) {
            return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
          }

          const synthesisProvider = 'openrouter';
          const synthesisKey = apiKeysResult.value.openrouter;
          if (synthesisKey === undefined) {
            return await reply.fail(
              'MISCONFIGURED',
              `API key required for synthesis with ${synthesisModel}`
            );
          }

          await researchRepo.update(id, {
            partialFailure: {
              ...partialFailure,
              userDecision: 'proceed',
            },
          });

          const services = getServices();
          const { synthesizer, contextInferrer } = createSynthesisProviders(
            synthesisModel,
            apiKeysResult.value, // @allow-result-access -- apiKeysResult.ok narrowed earlier in handler
            user.userId,
            services,
            request.log,
            id
          );

          const synthesisResult = await runSynthesis(id, {
            researchRepo,
            synthesizer,
            notificationSender,
            shareStorage,
            shareConfig,
            imageServiceClient,
            ...(contextInferrer !== undefined && { contextInferrer }),
            userId: user.userId,
            webAppUrl,
            reportLlmSuccess: (): void => {
              void userServiceClient.reportLlmSuccess(user.userId, synthesisProvider);
            },
            logger: {
              /* v8 ignore start -- ts-type: logger method with type narrowing for overloaded signature @preserve */
              info: (obj: object, msg?: string): void => {
              /* v8 ignore stop @preserve */
                request.log.info({ researchId: id, ...obj }, msg);
              },
              error: (obj: object, msg?: string): void => {
                /* v8 ignore start -- ts-type: type narrowing for overloaded logger signature @preserve */
                const message = typeof msg === 'string' ? msg : typeof obj === 'string' ? obj : undefined;
                /* v8 ignore stop @preserve */
                /* v8 ignore start -- ts-type: type narrowing for overloaded logger signature @preserve */
                const context = typeof obj === 'string' ? {} : obj;
                /* v8 ignore stop @preserve */
                /* v8 ignore start -- ts-type: type narrowing for overloaded logger signature @preserve */
                request.log.error({ researchId: id, ...context }, message);
                /* v8 ignore stop @preserve */
              },
              /* v8 ignore start -- ts-type: logger method with type narrowing for overloaded signature @preserve */
              warn: (obj: object, msg?: string): void => {
              /* v8 ignore stop @preserve */
                request.log.warn({ researchId: id, ...obj }, msg);
              },
              /* v8 ignore start -- ts-type: logger method with type narrowing for overloaded signature @preserve */
              debug: (obj: object, msg?: string): void => {
              /* v8 ignore stop @preserve */
                request.log.debug({ researchId: id, ...obj }, msg);
              },
            },
            notionServiceClient,
            researchExportSettings,
            researchCostSummaryClient: services.researchCostSummaryClient ?? null,
          });

          if (synthesisResult.ok) {
            return await reply.ok({
              action: 'proceed',
              message: 'Synthesis completed successfully',
            });
          }
          /* v8 ignore start -- ts-type: linkPreview.error narrowing after !ok — link-preview route, first guard @preserve */
          return await reply.fail('INTERNAL_ERROR', synthesisResult.error ?? 'Synthesis failed');
          /* v8 ignore stop @preserve */
        /* v8 ignore start -- ts-type: linkPreview.error narrowing after !ok — link-preview route, exhaustive-fallthrough close @preserve */
        }
        /* v8 ignore stop @preserve */

        case 'retry': {
          const unsupportedFailedModels = getUnsupportedHistoricalModels(partialFailure.failedModels);
          if (unsupportedFailedModels.length > 0) {
            return await reply.fail('CONFLICT', getUnsupportedRetryMessage(unsupportedFailedModels));
          }

          await researchRepo.update(id, {
            partialFailure: {
              ...partialFailure,
              userDecision: 'retry',
            },
          });

          const retryResult = await retryFailedLlms(id, { researchRepo, llmCallPublisher });

          if (retryResult.ok) {
            return await reply.ok({
              action: 'retry',
              /* v8 ignore start -- ts-type: noUncheckedIndexedAccess nullish coalescing fallback for retriedModels @preserve */
              message: `Retrying failed models: ${(retryResult.retriedModels ?? []).join(', ')}`,
              /* v8 ignore stop @preserve */
            });
          }
          /* v8 ignore start -- ts-type: richMetadata.error narrowing after !ok — link-preview route, second guard @preserve */
          return await reply.fail('INTERNAL_ERROR', retryResult.error ?? 'Retry failed');
          /* v8 ignore stop @preserve */
        /* v8 ignore start -- ts-type: richMetadata.error narrowing after !ok — link-preview route, exhaustive-fallthrough close @preserve */
        }
        /* v8 ignore stop @preserve */

        case 'cancel': {
          await researchRepo.update(id, {
            status: 'failed',
            synthesisError: 'Cancelled by user',
            completedAt: new Date().toISOString(),
            partialFailure: {
              ...partialFailure,
              userDecision: 'cancel',
            },
          });

          return await reply.ok({ action: 'cancel', message: 'Research cancelled' });
        }
      }
    }
  );

  // POST /research/:id/retry
  fastify.post(
    '/:id/retry',
    {
      schema: {
        operationId: 'retryFromFailed',
        summary: 'Retry from failed status',
        description:
          'Retry a failed research by re-running failed LLMs or synthesis. Idempotent: returns success if nothing to retry.',
        tags: ['research'],
        params: researchIdParamsSchema,
        response: {
          200: retryFromFailedResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/:id/retry',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const { id } = request.params as ResearchIdParams;
      const {
        researchRepo,
        userServiceClient,
        imageServiceClient,
        notificationSender,
        llmCallPublisher,
        shareStorage,
        shareConfig,
        webAppUrl,
        notionServiceClient,
        researchExportSettings,
        researchCostSummaryClient,
      } = getServices();

      const existing = await getResearch(id, { researchRepo });

      if (!existing.ok) {
        return await reply.fail('INTERNAL_ERROR', existing.error.message);
      }

      if (existing.value === null) {
        return await reply.fail('NOT_FOUND', 'Research not found');
      }

      if (existing.value.userId !== user.userId) {
        return await reply.fail('FORBIDDEN', 'Access denied');
      }

      const research = existing.value;
      const failedModels =
        research.status === 'failed'
          ? research.llmResults
              .filter((result) => result.status === 'failed')
              .map((result) => result.model)
          : [];
      const hasSynthesisError =
        research.synthesisError !== undefined && research.synthesisError !== '';
      const hasSuccessfulLlms = research.llmResults.some((result) => result.status === 'completed');
      const needsSynthesisRetry =
        research.status === 'failed' &&
        failedModels.length === 0 &&
        hasSynthesisError &&
        hasSuccessfulLlms;

      if (failedModels.length > 0) {
        const unsupportedFailedModels = getUnsupportedHistoricalModels(failedModels);
        if (unsupportedFailedModels.length > 0) {
          return await reply.fail('CONFLICT', getUnsupportedRetryMessage(unsupportedFailedModels));
        }
      } else if (needsSynthesisRetry) {
        if (!isExecutableSynthesisModel(research.synthesisModel)) {
          return await reply.fail(
            'CONFLICT',
            getUnsupportedSynthesisMessage(research.synthesisModel)
          );
        }
      }

      const retryDeps: Parameters<typeof retryFromFailed>[1] = {
        researchRepo,
        llmCallPublisher,
      };

      if (failedModels.length > 0 || needsSynthesisRetry) {
        const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
        if (!apiKeysResult.ok) {
          return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
        }

        const synthesisModel = research.synthesisModel;
        const synthesisProvider = 'openrouter';
        const synthesisKey = apiKeysResult.value.openrouter;
        if (synthesisKey === undefined) {
          return await reply.fail(
            'MISCONFIGURED',
            `API key required for synthesis with ${synthesisModel}`
          );
        }

        if (needsSynthesisRetry) {
          const { synthesizer, contextInferrer } = createSynthesisProviders(
            synthesisModel,
            apiKeysResult.value,
            user.userId,
            getServices(),
            request.log,
            id
          );
          retryDeps.synthesisDeps = {
            synthesizer,
            ...(contextInferrer !== undefined && { contextInferrer }),
            notificationSender,
            shareStorage,
            shareConfig,
            imageServiceClient,
            userId: user.userId,
            webAppUrl,
            reportLlmSuccess: (): void => {
              void userServiceClient.reportLlmSuccess(user.userId, synthesisProvider);
            },
            notionServiceClient,
            researchExportSettings,
            researchCostSummaryClient: researchCostSummaryClient ?? null,
            logger: request.log,
          };
        }
      }

      const retryResult = await retryFromFailed(id, retryDeps);

      if (!retryResult.ok) {
        if (retryResult.error?.startsWith('Cannot retry from status') === true) {
          return await reply.fail('CONFLICT', retryResult.error);
        }
        /* v8 ignore start -- ts-type: fetchSource.error narrowing after !ok — fetch-source route @preserve */
        return await reply.fail('INTERNAL_ERROR', retryResult.error ?? 'Retry failed');
        /* v8 ignore stop @preserve */
      /* v8 ignore start -- ts-type: fetchSource.error narrowing after !ok — fetch-source route, exhaustive-fallthrough close @preserve */
      }
      /* v8 ignore stop @preserve */

      const messages: Record<string, string> = {
        /* v8 ignore start -- ts-type: noUncheckedIndexedAccess nullish coalescing fallback for retriedModels @preserve */
        retried_llms: `Retrying failed models: ${(retryResult.retriedModels ?? []).join(', ')}`,
        /* v8 ignore stop @preserve */
        retried_synthesis: 'Re-running synthesis',
        already_completed: 'Research is already completed',
      };

      return await reply.ok({
        action: retryResult.action,
        /* v8 ignore start -- ts-type: action is keyof Messages but TypeScript can't narrow ?? fallback @preserve */
        message: messages[retryResult.action ?? 'already_completed'],
        /* v8 ignore stop @preserve */
        /* v8 ignore start -- ts-type: conditional spread filtered by undefined check @preserve */
        ...(retryResult.retriedModels !== undefined && {
        /* v8 ignore stop @preserve */
          retriedModels: retryResult.retriedModels,
        }),
      });
    }
  );

  // POST /research/:id/enhance
  fastify.post(
    '/:id/enhance',
    {
      schema: {
        operationId: 'enhanceResearch',
        summary: 'Enhance completed research',
        description:
          'Create a new research based on a completed one, reusing successful LLM results and adding new providers or contexts.',
        tags: ['research'],
        params: researchIdParamsSchema,
        body: enhanceResearchBodySchema,
        response: {
          201: enhanceResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'POST /research/:id/enhance',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const { id } = request.params as ResearchIdParams;
      const body = request.body as EnhanceResearchBody;
      const {
        researchRepo,
        generateId,
        researchEventPublisher,
        userServiceClient,
        createTitleGenerator,
      } = getServices();

      const apiKeysResult = await userServiceClient.getApiKeys(user.userId);
      if (!apiKeysResult.ok) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch API keys');
      }
      const apiKeys = apiKeysResult.value;

      // Fetch source research to validate inherited synthesis model
      const sourceResult = await researchRepo.findById(id);
      if (!sourceResult.ok) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch source research');
      }
      /* v8 ignore start -- upstream: prior check validated result.ok; null branch is not reachable when Firestore doc always exists in tests @preserve */
      if (sourceResult.value === null) {
      /* v8 ignore stop @preserve */
        return await reply.fail('NOT_FOUND', 'Source research not found');
      }
      const sourceResearch = sourceResult.value;

      if (body.additionalModels !== undefined && body.additionalModels.length > 0) {
        if (apiKeys.openrouter === undefined || apiKeys.openrouter === '') {
          return await reply.fail(
            'MISCONFIGURED',
            'OpenRouter API key is required for research enhancement'
          );
        }

        const copiedModels = sourceResearch.llmResults
          .filter((result) => result.status === 'completed')
          .map((result) => result.model);
        const enhancedModelCount = new Set([...copiedModels, ...body.additionalModels]).size;
        if (enhancedModelCount > 6) {
          return await reply.fail(
            'INVALID_REQUEST',
            'Enhanced research cannot contain more than 6 unique models'
          );
        }
      }

      // Validate synthesis model - use explicit or inherited from source
      const effectiveSynthesisModel = body.synthesisModel ?? sourceResearch.synthesisModel;
      if (!isExecutableSynthesisModel(effectiveSynthesisModel)) {
        return await reply.fail(
          'CONFLICT',
          getUnsupportedSynthesisMessage(effectiveSynthesisModel)
        );
      }
      if (apiKeys.openrouter === undefined || apiKeys.openrouter === '') {
        return await reply.fail(
          'MISCONFIGURED',
          `API key required for synthesis with ${effectiveSynthesisModel}`
        );
      }

      const enhanceInput: Parameters<typeof enhanceResearch>[0] = {
        sourceResearchId: id,
        userId: user.userId,
      };
      const enhancedResearchId = generateId();
      if (body.additionalModels !== undefined) {
        enhanceInput.additionalModels = body.additionalModels;
      }
      if (body.additionalContexts !== undefined) {
        const contextsWithLabels = await generateContextLabels(
          body.additionalContexts,
          apiKeys.openrouter,
          user.userId,
          createTitleGenerator,
          request.log,
          enhancedResearchId
        );
        enhanceInput.additionalContexts = contextsWithLabels;
      }
      if (body.synthesisModel !== undefined) {
        enhanceInput.synthesisModel = body.synthesisModel;
      }
      if (body.removeContextIds !== undefined) {
        enhanceInput.removeContextIds = body.removeContextIds;
      }

      const result = await enhanceResearch(enhanceInput, {
        researchRepo,
        generateId: () => enhancedResearchId,
        logger: request.log as unknown as Logger,
      });

      if (!result.ok) {
        switch (result.error.type) {
          case 'NOT_FOUND':
            return await reply.fail('NOT_FOUND', 'Research not found');
          case 'FORBIDDEN':
            return await reply.fail('FORBIDDEN', 'Access denied');
          case 'INVALID_STATUS':
            return await reply.fail(
              'CONFLICT',
              `Cannot enhance research in ${result.error.status} status`
            );
          case 'NO_CHANGES':
            return await reply.fail('CONFLICT', 'At least one change is required');
          case 'REPO_ERROR':
            return await reply.fail('INTERNAL_ERROR', result.error.error.message);
        }
      }

      // Publish to Pub/Sub for async processing
      await researchEventPublisher.publishProcessResearch({
        type: 'research.process',
        researchId: result.value.id, // @allow-result-access -- result.ok narrowed earlier in handler (outside 15-line hook window due to switch arms)
        userId: user.userId,
        triggeredBy: 'create',
      });

      return await reply.code(201).ok(result.value); // @allow-result-access -- result.ok narrowed earlier in handler (outside 15-line hook window due to switch arms)
    }
  );

  // DELETE /research/:id
  fastify.delete(
    '/:id',
    {
      schema: {
        operationId: 'deleteResearch',
        summary: 'Delete research',
        description: 'Delete a specific research.',
        tags: ['research'],
        params: researchIdParamsSchema,
        response: {
          200: deleteResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, { message: 'DELETE /research/:id' });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const params = request.params as ResearchIdParams;
      const { researchRepo } = getServices();

      // Check ownership first
      const existing = await getResearch(params.id, { researchRepo });
      if (!existing.ok || existing.value === null) {
        return await reply.fail('NOT_FOUND', 'Research not found');
      }

      if (existing.value.userId !== user.userId) {
        return await reply.fail('FORBIDDEN', 'Access denied');
      }

      const result = await deleteResearch(params.id, { researchRepo });

      if (!result.ok) {
        return await reply.fail('INTERNAL_ERROR', result.error.message);
      }

      return await reply.ok({});
    }
  );

  // DELETE /research/:id/share - Remove public share access
  fastify.delete(
    '/:id/share',
    {
      schema: {
        operationId: 'unshareResearch',
        summary: 'Remove public share access',
        description:
          'Remove public share access for a research by deleting the shared HTML and clearing shareInfo.',
        tags: ['research'],
        params: researchIdParamsSchema,
        response: {
          200: deleteResearchResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, { message: 'DELETE /research/:id/share' });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const params = request.params as ResearchIdParams;
      const { researchRepo, shareStorage, imageServiceClient } = getServices();

      const result = await unshareResearch(params.id, user.userId, {
        researchRepo,
        shareStorage,
        imageServiceClient,
        logger: request.log,
      });

      if (!result.ok) {
        if (result.error === 'Research not found') {
          return await reply.fail('NOT_FOUND', result.error);
        }
        if (result.error === 'Access denied') {
          return await reply.fail('FORBIDDEN', result.error);
        }
        if (result.error === 'Research is not shared') {
          return await reply.fail('CONFLICT', result.error);
        }
        /* v8 ignore start -- ts-type: researchSubmit.error narrowing after !ok — submit-research route @preserve */
        return await reply.fail('INTERNAL_ERROR', result.error ?? 'Failed to unshare');
        /* v8 ignore stop @preserve */
      /* v8 ignore start -- ts-type: researchSubmit.error narrowing after !ok — submit-research route, exhaustive-fallthrough close @preserve */
      }
      /* v8 ignore stop @preserve */

      return await reply.ok(null);
    }
  );

  // PATCH /research/:id/favourite - Toggle favourite status
  fastify.patch(
    '/:id/favourite',
    {
      schema: {
        operationId: 'toggleFavourite',
        summary: 'Toggle research favourite status',
        description: 'Mark or unmark a research as a favourite.',
        tags: ['research'],
        params: researchIdParamsSchema,
        body: toggleFavouriteBodySchema,
        response: {
          200: toggleFavouriteResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'PATCH /research/:id/favourite',
        bodyPreviewLength: 200,
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const { id } = request.params as ResearchIdParams;
      const body = request.body as { favourite: boolean };
      const { researchRepo } = getServices();

      const result = await toggleResearchFavourite(
        { researchId: id, userId: user.userId, favourite: body.favourite },
        { researchRepo }
      );

      if (!result.ok) {
        switch (result.error.type) {
          case 'NOT_FOUND':
            return await reply.fail('NOT_FOUND', 'Research not found');
          case 'FORBIDDEN':
            return await reply.fail('FORBIDDEN', 'Access denied');
          case 'REPO_ERROR':
            return await reply.fail('INTERNAL_ERROR', result.error.error.message);
        }
      }

      return await reply.ok(result.value);
    }
  );

  // POST /research/:id/export-notion
  fastify.post(
    '/:id/export-notion',
    {
      schema: {
        operationId: 'exportResearchToNotion',
        summary: 'Manually export research to Notion',
        description:
          'Manually trigger export of completed research to Notion. Requires Notion integration to be configured and connected.',
        tags: ['research'],
        params: researchIdParamsSchema,
        response: {
          200: exportNotionResponseSchema,
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      logIncomingRequest(request, {
        message: 'Received request to POST /research/:id/export-notion',
      });

      const user = await requireAuth(request, reply);
      if (user === null) {
        return;
      }

      const { id } = request.params as ResearchIdParams;
      const {
        researchRepo,
        notionServiceClient,
        researchExportSettings,
        notionExporter,
      } = getServices();

      // Fetch research
      const existingResult = await researchRepo.findById(id);
      if (!existingResult.ok) {
        return await reply.fail('INTERNAL_ERROR', existingResult.error.message);
      }
      if (existingResult.value === null) {
        return await reply.fail('NOT_FOUND', 'Research not found');
      }
      const research = existingResult.value;

      // Check ownership
      if (research.userId !== user.userId) {
        return await reply.fail('FORBIDDEN', 'Access denied');
      }

      // Check if research is completed
      if (research.status !== 'completed') {
        return await reply.fail('RESEARCH_NOT_COMPLETED', 'Research must be completed before exporting to Notion');
      }

      // Check if synthesis exists
      if (research.synthesizedResult === undefined || research.synthesizedResult === '') {
        return await reply.fail('NO_SYNTHESIS', 'Research has no synthesis to export');
      }

      // Check if already exported
      if (research.notionExportInfo !== undefined) {
        return await reply.fail('ALREADY_EXPORTED', 'Research has already been exported to Notion');
      }

      // Get user's Notion token
      const tokenResult = await notionServiceClient.getNotionToken(user.userId);
      if (!tokenResult.ok) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch Notion token');
      }
      const tokenContext = tokenResult.value;
      if (tokenContext.token === null || tokenContext.token === '') {
        return await reply.fail('NOTION_NOT_CONNECTED', 'Notion is not connected. Please connect your Notion account first.');
      }

      // Get user's Notion page ID configuration
      const pageIdResult = await researchExportSettings.getResearchPageId(user.userId);
      if (!pageIdResult.ok) {
        return await reply.fail('INTERNAL_ERROR', 'Failed to fetch Notion page configuration');
      }
      const targetPageId = pageIdResult.value;
      if (targetPageId === null || targetPageId === '') {
        return await reply.fail('PAGE_NOT_CONFIGURED', 'Notion research page is not configured. Please configure it in settings.');
      }

      // Export to Notion
      const notionLogger = {
        info: (msg: string, data?: Record<string, unknown>): void => {
          request.log.info({ ...data, msg });
        },
        warn: (msg: string, data?: Record<string, unknown>): void => {
          request.log.warn({ ...data, msg });
        },
        error: (msg: string, data?: Record<string, unknown>): void => {
          request.log.error({ ...data, msg });
        },
        debug: (msg: string, data?: Record<string, unknown>): void => {
          request.log.debug({ ...data, msg });
        },
      };

      const exportResult = await notionExporter(
        research,
        tokenContext.token,
        targetPageId,
        notionLogger
      );

      if (!exportResult.ok) {
        const error = exportResult.error;
        switch (error.code) {
          case 'UNAUTHORIZED':
            return await reply.code(401).fail('NOTION_UNAUTHORIZED', 'Notion token is invalid or expired. Please reconnect Notion.');
          case 'RATE_LIMITED':
            return await reply.code(429).fail('RATE_LIMITED', 'Notion API rate limit exceeded. Please try again later.');
          default:
            return await reply.fail('INTERNAL_ERROR', error.message);
        }
      }

      const { mainPageUrl, mainPageId, llmReportPages } = exportResult.value;

      // Save notionExportInfo to research document
      const notionExportInfo = {
        mainPageId,
        mainPageUrl,
        llmReportPageIds: llmReportPages.map((p) => ({
          model: p.model,
          pageId: p.pageId,
        })),
        exportedAt: new Date().toISOString(),
      };

      const saveResult = await researchRepo.update(id, { notionExportInfo });
      if (!saveResult.ok) {
        request.log.warn({ researchId: id, error: saveResult.error.message }, 'Failed to save Notion export info');
        // Return the research with notionExportInfo manually added since save failed
        return await reply.ok({ ...research, notionExportInfo });
      }

      // Return updated research with notionExportInfo populated
      const updatedResearchResult = await researchRepo.findById(id);
      if (!updatedResearchResult.ok || updatedResearchResult.value === null) {
        request.log.warn({ researchId: id }, 'Failed to fetch updated research after Notion export');
        // Return the original research with notionExportInfo manually added
        return await reply.ok({ ...research, notionExportInfo });
      }

      return await reply.ok(updatedResearchResult.value);
    }
  );

  done();
};
