// Generated by scripts/generate-service-wiring.mjs. Do not edit by hand.

export const WEB_SERVICE_URLS = [
  { envVar: 'INTEXURAOS_USER_SERVICE_URL', apiPath: '/api/user', proxyTarget: 'http://localhost:8110' },
  { envVar: 'INTEXURAOS_WHATSAPP_SERVICE_URL', apiPath: '/api/whatsapp', proxyTarget: 'http://localhost:8113' },
  { envVar: 'INTEXURAOS_NOTION_SERVICE_URL', apiPath: '/api/notion', proxyTarget: 'http://localhost:8112' },
  { envVar: 'INTEXURAOS_MOBILE_NOTIFICATIONS_SERVICE_URL', apiPath: '/api/notifications', proxyTarget: 'http://localhost:8114' },
  { envVar: 'INTEXURAOS_MESSAGE_DIGEST_SERVICE_URL', apiPath: '/api/message-digests', proxyTarget: 'http://localhost:8135' },
  { envVar: 'INTEXURAOS_FISHING_ASSISTANT_SERVICE_URL', apiPath: '/api/fishing-assistant', proxyTarget: 'http://localhost:8119' },
  { envVar: 'INTEXURAOS_RESEARCH_AGENT_URL', apiPath: '/api/research', proxyTarget: 'http://localhost:8116' },
  { envVar: 'INTEXURAOS_NOTES_AGENT_URL', apiPath: '/api/notes', proxyTarget: 'http://localhost:8121' },
  { envVar: 'INTEXURAOS_BOOKMARKS_AGENT_URL', apiPath: '/api/bookmarks', proxyTarget: 'http://localhost:8124' },
  { envVar: 'INTEXURAOS_CALENDAR_AGENT_URL', apiPath: '/api/calendar', proxyTarget: 'http://localhost:8125' },
  { envVar: 'INTEXURAOS_LINEAR_AGENT_URL', apiPath: '/api/linear', proxyTarget: 'http://localhost:8126' },
  { envVar: 'INTEXURAOS_CODE_AGENT_URL', apiPath: '/api/code', proxyTarget: 'http://localhost:8128' },
  { envVar: 'INTEXURAOS_IMAGE_SERVICE_URL', apiPath: '/api/images', proxyTarget: 'http://localhost:8120' },
  { envVar: 'INTEXURAOS_WEB_AGENT_URL', apiPath: '/api/web', proxyTarget: 'http://localhost:8127' },
  { envVar: 'INTEXURAOS_APP_SETTINGS_SERVICE_URL', apiPath: '/api/settings', proxyTarget: 'http://localhost:8122' },
  { envVar: 'INTEXURAOS_HELLSCRIPT_AGENT_URL', apiPath: '/api/hellscript-agent', proxyTarget: 'http://localhost:8131' },
  { envVar: 'INTEXURAOS_LLM_USAGE_SERVICE_URL', apiPath: '/api/llm-usage', proxyTarget: 'http://localhost:8132' },
  { envVar: 'INTEXURAOS_INTEX_AGENT_URL', apiPath: '/api/intex-agent', proxyTarget: 'http://localhost:8134' },
] as const;
