export const PUBLIC_WEB_ENV_KEYS = [
  'INTEXURAOS_AUTH0_DOMAIN',
  'INTEXURAOS_AUTH0_SPA_CLIENT_ID',
  'INTEXURAOS_AUTH_AUDIENCE',
  'INTEXURAOS_FIREBASE_PROJECT_ID',
  'INTEXURAOS_FIREBASE_API_KEY',
  'INTEXURAOS_FIREBASE_AUTH_DOMAIN',
  'INTEXURAOS_SENTRY_DSN_WEB',
  'INTEXURAOS_USE_FIREBASE_EMULATORS',
] as const;

export type PublicWebEnvKey = (typeof PUBLIC_WEB_ENV_KEYS)[number];

export function readPublicWebEnv(): Record<PublicWebEnvKey, string | undefined> {
  return {
    INTEXURAOS_AUTH0_DOMAIN: import.meta.env.INTEXURAOS_AUTH0_DOMAIN,
    INTEXURAOS_AUTH0_SPA_CLIENT_ID: import.meta.env.INTEXURAOS_AUTH0_SPA_CLIENT_ID,
    INTEXURAOS_AUTH_AUDIENCE: import.meta.env.INTEXURAOS_AUTH_AUDIENCE,
    INTEXURAOS_FIREBASE_PROJECT_ID: import.meta.env.INTEXURAOS_FIREBASE_PROJECT_ID,
    INTEXURAOS_FIREBASE_API_KEY: import.meta.env.INTEXURAOS_FIREBASE_API_KEY,
    INTEXURAOS_FIREBASE_AUTH_DOMAIN: import.meta.env.INTEXURAOS_FIREBASE_AUTH_DOMAIN,
    INTEXURAOS_SENTRY_DSN_WEB: import.meta.env.INTEXURAOS_SENTRY_DSN_WEB,
    INTEXURAOS_USE_FIREBASE_EMULATORS:
      import.meta.env.INTEXURAOS_USE_FIREBASE_EMULATORS,
  };
}
