/**
 * HTTP Contracts package - shared API contract definitions.
 *
 * This package provides:
 * - OpenAPI schema definitions for IntexuraOS APIs
 * - Fastify JSON Schemas for route validation
 * - Reusable schema patterns across services
 */

// OpenAPI schemas for swagger configuration
export {
  ERROR_CODES,
  ErrorCodeSchema,
  DiagnosticsSchema,
  ErrorBodySchema,
  ApiOkSchema,
  ApiErrorSchema,
  HealthCheckSchema,
  HealthResponseSchema,
  coreComponentSchemas,
  contractComponentSchemas,
  bearerAuthSecurityScheme,
} from './openapi-schemas.js';

// Fastify schemas for route validation
export {
  fastifyDiagnosticsSchema,
  fastifyErrorCodeSchema,
  fastifyErrorBodySchema,
  contractFastifySchemas,
  registerCoreSchemas,
} from './fastify-schemas.js';

export {
  bookmarksBookmarkResponseSchema,
  bookmarksBookmarkSchema,
  bookmarksCreateBookmarkDataSchema,
  bookmarksCreateBookmarkRequestSchema,
  bookmarksCreateBookmarkResponseSchema,
  imageGenerateImageRequestSchema,
  imageGenerateImageResponseSchema,
  imageGeneratePromptRequestSchema,
  imageGeneratePromptResponseSchema,
  imageGeneratedImageDataSchema,
  imageThumbnailPromptSchema,
  notesCreateNoteRequestSchema,
  notesCreateNoteResponseSchema,
  notionPagePreviewResponseSchema,
  notionPagePreviewSchema,
  notionTokenContextResponseSchema,
  notionTokenContextSchema,
  researchCreateDraftRequestSchema,
  researchCreateDraftResponseSchema,
  calendarCreateEventDataSchema,
  calendarCreateEventInputSchema,
  calendarCreateEventRequestSchema,
  calendarCreateEventResponseSchema,
  calendarUpdateEventAttendeesDataSchema,
  calendarUpdateEventAttendeesRequestSchema,
  calendarUpdateEventAttendeesResponseSchema,
  calendarUpdateEventChangesSchema,
  calendarUpdateEventDataSchema,
  calendarUpdateEventRequestSchema,
  calendarUpdateEventResponseSchema,
  calendarCreatedEventSchema,
  calendarEventDateTimeSchema,
  calendarListEventSchema,
  calendarListEventsDataSchema,
  calendarListEventsRequestSchema,
  calendarListEventsResponseSchema,
  calendarProcessActionRequestSchema,
  calendarProcessActionResponseSchema,
  calendarPreviewSchema,
  calendarPreviewDataSchema,
  calendarPreviewEnvelopeSchema,
  calendarPreviewResponseSchema,
  calendarGeneratePreviewRequestSchema,
  linearProcessActionRequestSchema,
  linearProcessActionResponseSchema,
  serviceFeedbackZodSchema,
  webAgentFetchLinkPreviewsRequestSchema,
  webAgentFetchLinkPreviewsResponseSchema,
  webAgentLinkPreviewMetadataSchema,
  webAgentLinkPreviewResultSchema,
  webAgentLinkPreviewSchema,
  webAgentPageSummaryMetadataSchema,
  webAgentPageSummaryResultSchema,
  webAgentPageSummarySchema,
  webAgentSummarizePageRequestSchema,
  webAgentSummarizePageResponseSchema,
  type BookmarksBookmark,
  type BookmarksCreateBookmarkData,
  type BookmarksCreateBookmarkRequest,
  type ImageGeneratedImageData,
  type ImageGenerateImageRequest,
  type ImageGeneratePromptRequest,
  type ImageThumbnailPrompt,
  type NotesCreateNoteRequest,
  type NotionPagePreview,
  type NotionTokenContext,
  type ResearchCreateDraftRequest,
  type CalendarCreateEventData,
  type CalendarCreateEventInput,
  type CalendarCreateEventRequest,
  type CalendarCreateEventResponse,
  type CalendarUpdateEventAttendeesData,
  type CalendarUpdateEventAttendeesRequest,
  type CalendarUpdateEventAttendeesResponse,
  type CalendarUpdateEventChanges,
  type CalendarUpdateEventData,
  type CalendarUpdateEventRequest,
  type CalendarUpdateEventResponse,
  type CalendarCreatedEvent,
  type CalendarEventDateTime,
  type CalendarListEvent,
  type CalendarListEventsData,
  type CalendarListEventsRequest,
  type CalendarListEventsResponse,
  type CalendarProcessActionRequest,
  type CalendarPreview,
  type CalendarPreviewData,
  type CalendarPreviewEnvelope,
  type CalendarPreviewResponse,
  type CalendarGeneratePreviewRequest,
  type LinearProcessActionRequest,
  type WebAgentFetchLinkPreviewsData,
  type WebAgentFetchLinkPreviewsRequest,
  type WebAgentLinkPreview,
  type WebAgentPageSummary,
  type WebAgentSummarizePageData,
  type WebAgentSummarizePageRequest,
} from './zod/index.js';

export {
  MATRIX_CORPUS_MAX_HEADER_CODE_UNITS,
  MATRIX_CORPUS_MAX_VISIBLE_MESSAGE_CODE_UNITS,
  MATRIX_CORPUS_MAX_CAPABILITY_TTL_MILLISECONDS,
  MATRIX_CORPUS_MAX_MOCK_PROFILE_UTF8_BYTES,
  MATRIX_CORPUS_MAX_JWS_PAYLOAD_SEGMENT_CODE_UNITS,
  MATRIX_CORPUS_MAX_COMPACT_JWS_CODE_UNITS,
  MATRIX_CORPUS_SCENARIO_TOTAL,
  MATRIX_CORPUS_DEFAULT_AGENT_MODEL,
  MATRIX_CORPUS_MINIMAX_AGENT_MODEL,
  MATRIX_CORPUS_AGENT_MODELS,
  MATRIX_CORPUS_EVALUATOR_MODEL,
  MATRIX_CORPUS_LEGACY_RUNTIME_AUDIENCE,
  MATRIX_CORPUS_PRODUCTION_RUNTIME_AUDIENCE,
  MATRIX_CORPUS_VISIBLE_VERSION,
  matrixCorpusCapabilityTokenSchema,
  matrixCorpusSha256DigestSchema,
  matrixCorpusKeyedDigestSchema,
  matrixCorpusDecimalFenceSchema,
  matrixCorpusSafeIdSchema,
  matrixCorpusTransportMessageIdSchema,
  matrixCorpusRfc3339TimestampSchema,
  matrixCorpusIanaTimeZoneSchema,
  matrixCorpusRuntimeAudienceSchema,
  matrixCorpusAgentModelSchema,
  matrixCorpusEvaluatorModelSchema,
  matrixCorpusPromptDigestInputSchema,
  matrixCorpusVisibleConfirmationHeaderV1Schema,
  matrixCorpusVisibleStartHeaderV1Schema,
  matrixCorpusVisibleTurnHeaderV1Schema,
  intexAgentToolNameV1Schema,
  strictMockResultV1Schema,
  strictToolMockProfileV1Schema,
  matrixCorpusExpectedToolScheduleV1Schema,
  matrixCorpusParsedIngressFactsV1Schema,
  matrixCorpusIngestContextV1Schema,
  matrixCorpusOrdinaryIngestV1Schema,
  matrixCorpusAttestedIngestPayloadV1Schema,
  matrixCorpusCapabilityIssueRequestV1Schema,
  matrixCorpusCapabilityIssueDigestInputV1Schema,
  matrixCorpusCapabilityV1Schema,
  matrixCorpusCapabilityIssueResponseV1Schema,
  matrixCorpusCanonicalIngressDigestInputV1Schema,
  matrixCorpusCapabilityConsumeFactsV1Schema,
  matrixCorpusTerminalControlV1Schema,
  matrixCorpusControlMutationV1Schema,
  matrixCorpusControlMutationOperationV1Schema,
  matrixCorpusControlRequestDigestInputV1Schema,
  matrixCorpusAttestationClaimsV1Schema,
  matrixCorpusSignedIngestV1Schema,
  matrixCorpusSignedTerminalControlV1Schema,
  matrixCorpusSignedControlMutationV1Schema,
  canonicalMatrixCorpusStrictToolMockProfileV1,
  canonicalMatrixCorpusCapabilityIssueDigestInputV1,
  canonicalMatrixCorpusIngressRequestV1,
  canonicalMatrixCorpusIngestPayloadV1,
  canonicalMatrixCorpusTerminalControlV1,
  canonicalMatrixCorpusControlMutationV1,
  canonicalMatrixCorpusControlRequestDigestInputV1,
  type IntexAgentToolNameV1,
  type StrictMockResultV1,
  type StrictToolMockProfileV1,
  type MatrixCorpusExpectedToolScheduleV1,
  type MatrixCorpusParsedIngressFactsV1,
  type MatrixCorpusIngestContextV1,
  type MatrixCorpusOrdinaryIngestV1,
  type MatrixCorpusAttestedIngestPayloadV1,
  type MatrixCorpusCapabilityIssueRequestV1,
  type MatrixCorpusCapabilityIssueDigestInputV1,
  type MatrixCorpusCapabilityV1,
  type MatrixCorpusCapabilityIssueResponseV1,
  type MatrixCorpusCanonicalIngressDigestInputV1,
  type MatrixCorpusCapabilityConsumeFactsV1,
  type MatrixCorpusTerminalControlV1,
  type MatrixCorpusControlMutationV1,
  type MatrixCorpusControlRequestDigestInputV1,
  type MatrixCorpusAttestationClaimsV1,
  type MatrixCorpusSignedIngestV1,
  type MatrixCorpusSignedTerminalControlV1,
  type MatrixCorpusSignedControlMutationV1,
  type MatrixCorpusReservedHeaderReason,
  type MatrixCorpusVisibleHeaderV1,
  type MatrixCorpusVisibleMessageParseResult,
  type MatrixCorpusVisiblePhase,
  type MatrixCorpusRuntimeAudience,
  type MatrixCorpusAgentModel,
  type MatrixCorpusEvaluatorModel,
} from './matrixCorpus.js';

export {
  INTEX_AGENT_TEST_RUN_SCENARIO_COUNT,
  INTEX_AGENT_TEST_RUN_MAX_TOOL_EVIDENCE,
  INTEX_AGENT_TEST_RUN_MAX_TOOL_FACTS,
  INTEX_AGENT_TEST_RUN_MAX_DETERMINISTIC_CHECKS,
  INTEX_AGENT_TEST_RUN_MAX_REPLY_EVALUATIONS,
  INTEX_AGENT_TEST_RUN_MAX_AGENT_USAGE,
  INTEX_AGENT_TEST_RUN_MAX_AGENT_CALL_ORDINAL,
  INTEX_AGENT_TEST_RUN_MAX_REPLIES_PER_TURN,
  sanitizeIntexAgentReplyText,
  classifyIntexAgentReplyDatePresentation,
  type IntexAgentReplyDatePresentation,
  testRunLifecycleSchema,
  testScenarioLifecycleSchema,
  testVerdictSchema,
  testArtifactDeliveryV1Schema,
  testRunTotalsV1Schema,
  testRunCostV1Schema,
  publicTestRunScenarioSummaryV1Schema,
  publicTestRunHeaderV1Schema,
  safeToolFactNameV1Schema,
  safeToolFactV1Schema,
  safeExpectedToolFactV1Schema,
  safeToolEvidenceV1Schema,
  safeDeterministicEvidenceV1Schema,
  safeDeterministicCheckV1Schema,
  safeMiniMaxCriterionCodeV1Schema,
  safeReplyEvaluationV1Schema,
  safeAgentUsageV1Schema,
  testRunListDtoV1Schema,
  testRunDtoV1Schema,
  publicTestTimelineEventV1Schema,
  testScenarioDtoV1Schema,
  type TestRunLifecycle,
  type TestScenarioLifecycle,
  type TestVerdict,
  type TestArtifactDeliveryV1,
  type TestRunTotalsV1,
  type TestRunCostV1,
  type PublicTestRunScenarioSummaryV1,
  type PublicTestRunHeaderV1,
  type SafeToolFactV1,
  type SafeExpectedToolFactV1,
  type SafeToolEvidenceV1,
  type SafeDeterministicEvidenceV1,
  type SafeDeterministicCheckV1,
  type SafeReplyEvaluationV1,
  type SafeAgentUsageV1,
  type TestRunListDtoV1,
  type TestRunDtoV1,
  type PublicTestTimelineEventV1,
  type TestScenarioDtoV1,
} from './intexAgentTestRuns.js';

export { WHATSAPP_INTERACTIVE_BODY_MAX_LENGTH } from './whatsapp.js';
