# Manual trigger: Deploy llm-orchestrator only
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use --name builder 2>/dev/null || docker buildx use builder
        docker buildx build \
          --cache-from=type=registry,ref=${_ARTIFACT_REGISTRY_URL}/llm-orchestrator:buildcache \
          --cache-to=type=registry,ref=${_ARTIFACT_REGISTRY_URL}/llm-orchestrator:buildcache,mode=max \
          --push \
          -t ${_ARTIFACT_REGISTRY_URL}/llm-orchestrator:$COMMIT_SHA \
          -t ${_ARTIFACT_REGISTRY_URL}/llm-orchestrator:latest \
          -f apps/llm-orchestrator/Dockerfile .
    env: ['DOCKER_BUILDKIT=1']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args: ['-c', 'bash cloudbuild/scripts/deploy-llm-orchestrator.sh']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REGION=${_REGION}'
      - 'ARTIFACT_REGISTRY_URL=${_ARTIFACT_REGISTRY_URL}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: '600s'

