import type { FastifyInstance } from 'fastify';

type JsonSchema = Record<string, unknown>;

const messageType = {
  type: 'string',
  enum: [
    'text',
    'image',
    'audio',
    'video',
    'file',
    'sticker',
    'reaction',
    'redaction',
    'unknown',
  ],
};

const direction = { type: 'string', enum: ['incoming', 'outgoing'] };
const dateTime = { type: 'string', format: 'date-time' };

const schemas: JsonSchema[] = [
  {
    $id: 'ConversationAssistantDateRange',
    type: 'object',
    additionalProperties: false,
    properties: { from: dateTime, to: dateTime },
    required: ['from', 'to'],
  },
  {
    $id: 'ConversationAssistantErrorValue',
    type: 'object',
    additionalProperties: false,
    properties: { code: { type: 'string' }, message: { type: 'string' } },
    required: ['code', 'message'],
  },
  {
    $id: 'ConversationAssistantPreparationErrorValue',
    type: 'object',
    additionalProperties: false,
    properties: {
      code: { type: 'string' },
      message: { type: 'string' },
      estimatedPromptTokens: { type: 'integer', minimum: 0 },
      promptTokenBudget: { type: 'integer', minimum: 0 },
      recommendedRange: { $ref: 'ConversationAssistantDateRange#' },
    },
    required: ['code', 'message'],
  },
  {
    $id: 'ConversationAssistantOmittedCounts',
    type: 'object',
    additionalProperties: false,
    properties: {
      mediaOnly: { type: 'integer', minimum: 0 },
      failedTranscriptions: { type: 'integer', minimum: 0 },
      pendingTranscriptions: { type: 'integer', minimum: 0 },
      nonText: { type: 'integer', minimum: 0 },
      overLimit: { type: 'integer', minimum: 0 },
    },
    required: [
      'mediaOnly',
      'failedTranscriptions',
      'pendingTranscriptions',
      'nonText',
      'overLimit',
    ],
  },
  {
    $id: 'ConversationAssistantUsage',
    type: 'object',
    additionalProperties: false,
    properties: {
      inputTokens: { type: 'number', minimum: 0 },
      outputTokens: { type: 'number', minimum: 0 },
      totalTokens: { type: 'number', minimum: 0 },
      costUsd: { type: 'number', minimum: 0 },
      cachedTokens: { type: 'number', minimum: 0 },
      cacheWriteTokens: { type: 'number', minimum: 0 },
    },
    required: ['inputTokens', 'outputTokens', 'totalTokens', 'costUsd'],
  },
  {
    $id: 'ConversationAssistantContinuationAvailable',
    type: 'object',
    additionalProperties: false,
    properties: {
      state: { type: 'string', enum: ['available'] },
      displayTimeZone: { type: 'string' },
    },
    required: ['state', 'displayTimeZone'],
  },
  {
    $id: 'ConversationAssistantContinuationUnavailable',
    type: 'object',
    additionalProperties: false,
    properties: {
      state: { type: 'string', enum: ['legacy_session', 'source_unavailable'] },
    },
    required: ['state'],
  },
  {
    $id: 'ConversationAssistantActiveTurn',
    type: 'object',
    additionalProperties: false,
    properties: {
      requestId: { type: 'string' },
      stateVersion: { type: 'integer', minimum: 0 },
    },
    required: ['requestId', 'stateVersion'],
  },
  {
    $id: 'ConversationAssistantContextSummary',
    type: 'object',
    additionalProperties: false,
    properties: {
      displayTimeZone: { type: 'string' },
      availability: {
        oneOf: [
          { $ref: 'ConversationAssistantContinuationAvailable#' },
          { $ref: 'ConversationAssistantContinuationUnavailable#' },
        ],
      },
      contextVersion: { type: 'integer', minimum: 0 },
      snapshotCount: { type: 'integer', minimum: 0 },
      totalAttachedMessageCount: { type: 'integer', minimum: 0 },
      totalAttachedOmittedCount: { type: 'integer', minimum: 0 },
      completedConversationRevision: { type: 'integer', minimum: 0 },
      activeTurn: {
        anyOf: [{ type: 'null' }, { $ref: 'ConversationAssistantActiveTurn#' }],
      },
    },
    required: [
      'displayTimeZone',
      'availability',
      'contextVersion',
      'snapshotCount',
      'totalAttachedMessageCount',
      'totalAttachedOmittedCount',
      'completedConversationRevision',
      'activeTurn',
    ],
  },
  {
    $id: 'ConversationAssistantSession',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string' },
      chatDisplayName: { type: 'string' },
      status: { type: 'string', enum: ['preparing', 'ready', 'failed', 'active'] },
      preparationStage: {
        type: 'string',
        enum: ['queued', 'loading_messages', 'building_context', 'ready', 'failed'],
      },
      preparationAttempt: { type: 'integer', minimum: 0 },
      preparationError: { $ref: 'ConversationAssistantPreparationErrorValue#' },
      range: { $ref: 'ConversationAssistantDateRange#' },
      effectiveRange: { $ref: 'ConversationAssistantDateRange#' },
      model: { type: 'string' },
      modelDisplayName: { type: 'string' },
      transcriptMessageCount: { type: 'integer', minimum: 0 },
      assistantRoleLabel: { type: 'string' },
      omitted: { $ref: 'ConversationAssistantOmittedCounts#' },
      title: { type: 'string' },
      createdAt: dateTime,
      updatedAt: dateTime,
      lastTurnAt: dateTime,
      deletionToken: { type: 'string' },
      deletionPending: { type: 'boolean' },
      contextSummary: { $ref: 'ConversationAssistantContextSummary#' },
    },
    required: [
      'id',
      'status',
      'range',
      'effectiveRange',
      'model',
      'modelDisplayName',
      'transcriptMessageCount',
      'assistantRoleLabel',
      'omitted',
      'title',
      'createdAt',
      'updatedAt',
      'deletionToken',
      'deletionPending',
      'contextSummary',
    ],
  },
  {
    $id: 'ConversationAssistantSessionResponse',
    type: 'object',
    additionalProperties: false,
    properties: { session: { $ref: 'ConversationAssistantSession#' } },
    required: ['session'],
  },
  {
    $id: 'ConversationAssistantSessionList',
    type: 'object',
    additionalProperties: false,
    properties: {
      sessions: { type: 'array', items: { $ref: 'ConversationAssistantSession#' } },
    },
    required: ['sessions'],
  },
  {
    $id: 'ConversationAssistantContextCheck',
    type: 'object',
    additionalProperties: false,
    properties: {
      messageCount: { type: 'integer', minimum: 0 },
      warningThreshold: { type: 'integer', minimum: 0 },
      requiresConfirmation: { type: 'boolean' },
    },
    required: ['messageCount', 'warningThreshold', 'requiresConfirmation'],
  },
  {
    $id: 'ConversationAssistantContextReaction',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string', pattern: '^context-reaction-' },
      emoji: { type: 'string' },
      senderDisplayName: { type: 'string' },
      direction,
      eventTimestamp: dateTime,
    },
    required: ['id', 'emoji', 'direction', 'eventTimestamp'],
  },
  {
    $id: 'ConversationAssistantContextMessage',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string', pattern: '^context-item-' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
      contentKind: { type: 'string', enum: ['text', 'transcription'] },
      content: { type: 'string' },
      reactions: {
        type: 'array',
        items: { $ref: 'ConversationAssistantContextReaction#' },
      },
    },
    required: [
      'id',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
      'contentKind',
      'content',
    ],
  },
  {
    $id: 'ConversationAssistantContextTargetReference',
    type: 'object',
    additionalProperties: false,
    properties: {
      emoji: { type: 'string' },
      targetReference: { type: 'string', pattern: '^context-item-' },
    },
    required: ['emoji'],
  },
  {
    $id: 'ConversationAssistantOmittedContextMessage',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string', pattern: '^context-item-' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
      omissionReason: {
        type: 'string',
        enum: [
          'media_only',
          'failed_transcription',
          'pending_transcription',
          'non_text',
          'over_limit',
        ],
      },
      contentKind: { type: 'string', enum: ['text', 'transcription'] },
      content: { type: 'string' },
      reactions: {
        type: 'array',
        items: { $ref: 'ConversationAssistantContextReaction#' },
      },
      reaction: { $ref: 'ConversationAssistantContextTargetReference#' },
    },
    required: [
      'id',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
      'omissionReason',
    ],
  },
  {
    $id: 'ConversationAssistantContext',
    type: 'object',
    additionalProperties: false,
    properties: {
      sessionId: { type: 'string' },
      messages: {
        type: 'array',
        items: { $ref: 'ConversationAssistantContextMessage#' },
      },
      omittedMessages: {
        type: 'array',
        items: { $ref: 'ConversationAssistantOmittedContextMessage#' },
      },
      messageCount: { type: 'integer', minimum: 0 },
      omittedMessageCount: { type: 'integer', minimum: 0 },
      snapshotAvailable: { type: 'boolean' },
      omitted: { $ref: 'ConversationAssistantOmittedCounts#' },
      nextMessageCursor: { type: 'integer', minimum: 0 },
      nextOmittedCursor: { type: 'integer', minimum: 0 },
    },
    required: [
      'sessionId',
      'messages',
      'omittedMessages',
      'messageCount',
      'omittedMessageCount',
      'snapshotAvailable',
      'omitted',
    ],
  },
  {
    $id: 'ConversationAssistantContextAttachmentCounts',
    type: 'object',
    additionalProperties: false,
    properties: {
      included: { type: 'integer', minimum: 0 },
      excluded: { type: 'integer', minimum: 0 },
      completedTranscriptions: { type: 'integer', minimum: 0 },
      edited: { type: 'integer', minimum: 0 },
      redacted: { type: 'integer', minimum: 0 },
      deleted: { type: 'integer', enum: [0] },
      reactionsChanged: { type: 'integer', minimum: 0 },
      lateIngested: { type: 'integer', minimum: 0 },
    },
    required: [
      'included',
      'excluded',
      'completedTranscriptions',
      'edited',
      'redacted',
      'reactionsChanged',
      'lateIngested',
    ],
  },
  {
    $id: 'ConversationAssistantContextAttachmentError',
    type: 'object',
    additionalProperties: false,
    properties: {
      code: {
        type: 'string',
        enum: ['ATTACHMENT_TOO_LARGE', 'PREPARATION_FAILED'],
      },
      message: { type: 'string' },
    },
    required: ['code', 'message'],
  },
  {
    $id: 'ConversationAssistantContextAttachment',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string' },
      status: {
        type: 'string',
        enum: ['preparing', 'ready', 'failed', 'expired', 'committed'],
      },
      compatibility: { type: 'string', enum: ['current', 'stale'] },
      capturedAt: dateTime,
      captureRange: { $ref: 'ConversationAssistantDateRange#' },
      eventRange: { $ref: 'ConversationAssistantDateRange#' },
      counts: { $ref: 'ConversationAssistantContextAttachmentCounts#' },
      omitted: { $ref: 'ConversationAssistantOmittedCounts#' },
      requiresConfirmation: { type: 'boolean' },
      confirmationToken: { type: 'string' },
      error: { $ref: 'ConversationAssistantContextAttachmentError#' },
      expiresAt: dateTime,
      newerAvailableCount: { type: 'integer', minimum: 0 },
      newerAvailableCorrectionCount: { type: 'integer', minimum: 0 },
    },
    required: [
      'id',
      'status',
      'compatibility',
      'capturedAt',
      'requiresConfirmation',
      'newerAvailableCount',
      'newerAvailableCorrectionCount',
    ],
  },
  {
    $id: 'ConversationAssistantContextAttachmentResponse',
    type: 'object',
    additionalProperties: false,
    properties: {
      attachment: { $ref: 'ConversationAssistantContextAttachment#' },
    },
    required: ['attachment'],
  },
  {
    $id: 'ConversationAssistantPreviewReaction',
    type: 'object',
    additionalProperties: false,
    properties: {
      emoji: { type: 'string' },
      senderDisplayName: { type: 'string' },
      direction,
      eventTimestamp: dateTime,
    },
    required: ['emoji', 'direction', 'eventTimestamp'],
  },
  {
    $id: 'ConversationAssistantIncludedPreviewMessage',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string', pattern: '^context-item-' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
      contentKind: { type: 'string', enum: ['text', 'transcription'] },
      content: { type: 'string' },
      reactions: { type: 'array', items: { $ref: 'ConversationAssistantPreviewReaction#' } },
    },
    required: [
      'id',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
      'contentKind',
      'content',
    ],
  },
  {
    $id: 'ConversationAssistantExcludedPreviewMessage',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string', pattern: '^context-item-' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
      omissionReason: {
        type: 'string',
        enum: [
          'media_only',
          'failed_transcription',
          'pending_transcription',
          'non_text',
          'over_limit',
        ],
      },
      contentKind: { type: 'string', enum: ['text', 'transcription'] },
      content: { type: 'string' },
      reactions: { type: 'array', items: { $ref: 'ConversationAssistantPreviewReaction#' } },
    },
    required: [
      'id',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
      'omissionReason',
    ],
  },
  {
    $id: 'ConversationAssistantCorrectionMissingProjection',
    type: 'object',
    additionalProperties: false,
    properties: { state: { type: 'string', enum: ['missing', 'unavailable'] } },
    required: ['state'],
  },
  {
    $id: 'ConversationAssistantCorrectionIncludedProjection',
    type: 'object',
    additionalProperties: false,
    properties: {
      state: { type: 'string', const: 'included' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
      contentKind: { type: 'string', enum: ['text', 'transcription'] },
      content: { type: 'string' },
      reactions: { type: 'array', items: { $ref: 'ConversationAssistantPreviewReaction#' } },
    },
    required: [
      'state',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
      'contentKind',
      'content',
      'reactions',
    ],
  },
  {
    $id: 'ConversationAssistantCorrectionOmittedProjection',
    type: 'object',
    additionalProperties: false,
    properties: {
      state: { type: 'string', const: 'omitted' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
      omissionReason: {
        type: 'string',
        enum: [
          'media_only',
          'failed_transcription',
          'pending_transcription',
          'non_text',
          'over_limit',
        ],
      },
      reactions: { type: 'array', items: { $ref: 'ConversationAssistantPreviewReaction#' } },
    },
    required: [
      'state',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
      'omissionReason',
      'reactions',
    ],
  },
  {
    $id: 'ConversationAssistantCorrectionRedactedProjection',
    type: 'object',
    additionalProperties: false,
    properties: {
      state: { type: 'string', const: 'redacted' },
      eventTimestamp: dateTime,
      importedAt: dateTime,
      direction,
      speakerLabel: { type: 'string' },
      messageType,
    },
    required: [
      'state',
      'eventTimestamp',
      'importedAt',
      'direction',
      'speakerLabel',
      'messageType',
    ],
  },
  {
    $id: 'ConversationAssistantCorrectionProjection',
    oneOf: [
      { $ref: 'ConversationAssistantCorrectionMissingProjection#' },
      { $ref: 'ConversationAssistantCorrectionIncludedProjection#' },
      { $ref: 'ConversationAssistantCorrectionOmittedProjection#' },
      { $ref: 'ConversationAssistantCorrectionRedactedProjection#' },
    ],
  },
  {
    $id: 'ConversationAssistantIncludedPreviewItem',
    type: 'object',
    additionalProperties: false,
    properties: {
      kind: { type: 'string', const: 'included' },
      message: { $ref: 'ConversationAssistantIncludedPreviewMessage#' },
    },
    required: ['kind', 'message'],
  },
  {
    $id: 'ConversationAssistantExcludedPreviewItem',
    type: 'object',
    additionalProperties: false,
    properties: {
      kind: { type: 'string', const: 'excluded' },
      message: { $ref: 'ConversationAssistantExcludedPreviewMessage#' },
    },
    required: ['kind', 'message'],
  },
  {
    $id: 'ConversationAssistantCorrectionPreviewItem',
    type: 'object',
    additionalProperties: false,
    properties: {
      kind: { type: 'string', const: 'correction' },
      changeKind: {
        type: 'string',
        enum: ['created', 'transcription_changed', 'edited', 'redacted', 'reaction_changed'],
      },
      targetReference: { type: 'string', pattern: '^context-item-' },
      before: { $ref: 'ConversationAssistantCorrectionProjection#' },
      after: { $ref: 'ConversationAssistantCorrectionProjection#' },
    },
    required: ['kind', 'changeKind', 'targetReference', 'before', 'after'],
  },
  {
    $id: 'ConversationAssistantPreviewItem',
    oneOf: [
      { $ref: 'ConversationAssistantIncludedPreviewItem#' },
      { $ref: 'ConversationAssistantExcludedPreviewItem#' },
      { $ref: 'ConversationAssistantCorrectionPreviewItem#' },
    ],
  },
  {
    $id: 'ConversationAssistantContextAttachmentPreviewPage',
    type: 'object',
    additionalProperties: false,
    properties: {
      items: { type: 'array', items: { $ref: 'ConversationAssistantPreviewItem#' } },
      nextCursor: { type: 'string' },
    },
    required: ['items'],
  },
  {
    $id: 'ConversationAssistantContextSnapshotSummary',
    type: 'object',
    additionalProperties: false,
    properties: {
      kind: { type: 'string', enum: ['initial', 'update'] },
      contextVersion: { type: 'integer', minimum: 0 },
      capturedAt: dateTime,
      messageCount: { type: 'integer', minimum: 0 },
      excludedCount: { type: 'integer', minimum: 0 },
      correctionCount: { type: 'integer', minimum: 0 },
      omitted: { $ref: 'ConversationAssistantOmittedCounts#' },
      attachmentId: { type: 'string' },
      linkedTurnId: { type: 'string' },
      captureRange: { $ref: 'ConversationAssistantDateRange#' },
      eventRange: { $ref: 'ConversationAssistantDateRange#' },
    },
    required: [
      'kind',
      'contextVersion',
      'capturedAt',
      'messageCount',
      'excludedCount',
      'correctionCount',
      'omitted',
    ],
  },
  {
    $id: 'ConversationAssistantContextHistory',
    type: 'object',
    additionalProperties: false,
    properties: {
      snapshots: {
        type: 'array',
        items: { $ref: 'ConversationAssistantContextSnapshotSummary#' },
      },
    },
    required: ['snapshots'],
  },
  {
    $id: 'ConversationAssistantTurnContextAttachment',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string' },
      capturedAt: dateTime,
      captureRange: { $ref: 'ConversationAssistantDateRange#' },
      eventRange: { $ref: 'ConversationAssistantDateRange#' },
      counts: { $ref: 'ConversationAssistantContextAttachmentCounts#' },
      omitted: { $ref: 'ConversationAssistantOmittedCounts#' },
    },
    required: ['id', 'capturedAt', 'captureRange', 'counts', 'omitted'],
  },
  {
    $id: 'ConversationAssistantTurn',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string' },
      sessionId: { type: 'string' },
      role: { type: 'string', enum: ['user', 'assistant'] },
      text: { type: 'string' },
      createdAt: dateTime,
      sequence: { type: 'integer', minimum: 0 },
      conversationRevision: { type: 'integer', minimum: 0 },
      requestId: { type: 'string' },
      canRetryAnswer: { type: 'boolean' },
      kind: { type: 'string', enum: ['message', 'context_attachment_question'] },
      contextAttachmentId: { type: 'string' },
      contextAttachment: { $ref: 'ConversationAssistantTurnContextAttachment#' },
      acknowledgment: { type: 'string' },
      usage: { $ref: 'ConversationAssistantUsage#' },
      error: { $ref: 'ConversationAssistantErrorValue#' },
    },
    required: ['id', 'sessionId', 'role', 'text', 'createdAt'],
  },
  {
    $id: 'ConversationAssistantTurnList',
    type: 'object',
    additionalProperties: false,
    properties: {
      turns: { type: 'array', items: { $ref: 'ConversationAssistantTurn#' } },
    },
    required: ['turns'],
  },
  {
    $id: 'ConversationAssistantTurnRequest',
    type: 'object',
    additionalProperties: false,
    properties: {
      id: { type: 'string' },
      sessionId: { type: 'string' },
      status: { type: 'string', enum: ['in_progress', 'completed', 'failed'] },
      attempt: { type: 'integer', minimum: 1 },
      stateVersion: { type: 'integer', minimum: 0 },
      conversationRevision: { type: 'integer', minimum: 0 },
      contextAttachmentId: { type: 'string' },
      completedAt: dateTime,
      error: { $ref: 'ConversationAssistantErrorValue#' },
    },
    required: [
      'id',
      'sessionId',
      'status',
      'attempt',
      'stateVersion',
      'conversationRevision',
    ],
  },
  {
    $id: 'ConversationAssistantTurnRequestRecovery',
    type: 'object',
    additionalProperties: false,
    properties: {
      request: { $ref: 'ConversationAssistantTurnRequest#' },
      turns: { type: 'array', items: { $ref: 'ConversationAssistantTurn#' } },
      canRetryAnswer: { type: 'boolean' },
    },
    required: ['request', 'turns', 'canRetryAnswer'],
  },
  {
    $id: 'ConversationAssistantSendTurn',
    oneOf: [
      { $ref: 'ConversationAssistantTurnList#' },
      { $ref: 'ConversationAssistantTurnRequestRecovery#' },
    ],
  },
  {
    $id: 'ConversationAssistantDeleted',
    type: 'object',
    additionalProperties: false,
    properties: { deleted: { type: 'boolean', const: true } },
    required: ['deleted'],
  },
  ...sseEventSchemas(),
];

export function registerConversationAssistantPublicSchemas(
  fastify: Pick<FastifyInstance, 'addSchema'>
): void {
  for (const schema of schemas) fastify.addSchema(schema);
}

function sseEventSchemas(): JsonSchema[] {
  const requestIdentity = {
    requestId: { type: 'string' },
    streamSequence: { type: 'integer', minimum: 1 },
  };
  const optionalIdentity = requestIdentity;
  return [
    {
      $id: 'ConversationAssistantSseRequestState',
      type: 'object',
      additionalProperties: false,
      properties: {
        type: { type: 'string', const: 'request_state' },
        ...requestIdentity,
        request: { $ref: 'ConversationAssistantTurnRequest#' },
      },
      required: ['type', 'requestId', 'streamSequence', 'request'],
    },
    {
      $id: 'ConversationAssistantSseContextAttached',
      type: 'object',
      additionalProperties: false,
      properties: {
        type: { type: 'string', const: 'context_attached' },
        ...requestIdentity,
        attachmentId: { type: 'string' },
      },
      required: ['type', 'requestId', 'streamSequence', 'attachmentId'],
    },
    sseOptionalIdentityEvent(
      'ConversationAssistantSseUserTurn',
      'user_turn',
      { turn: { $ref: 'ConversationAssistantTurn#' } },
      ['turn'],
      optionalIdentity
    ),
    sseOptionalIdentityEvent(
      'ConversationAssistantSseAssistantDelta',
      'assistant_delta',
      { text: { type: 'string' } },
      ['text'],
      optionalIdentity
    ),
    sseOptionalIdentityEvent(
      'ConversationAssistantSseUsage',
      'usage',
      { usage: { $ref: 'ConversationAssistantUsage#' } },
      ['usage'],
      optionalIdentity
    ),
    sseOptionalIdentityEvent(
      'ConversationAssistantSseError',
      'error',
      { error: { $ref: 'ConversationAssistantErrorValue#' } },
      ['error'],
      optionalIdentity
    ),
    sseOptionalIdentityEvent(
      'ConversationAssistantSseAssistantTurn',
      'assistant_turn',
      { turn: { $ref: 'ConversationAssistantTurn#' } },
      ['turn'],
      optionalIdentity
    ),
    sseOptionalIdentityEvent(
      'ConversationAssistantSseDone',
      'done',
      {},
      [],
      optionalIdentity
    ),
    {
      $id: 'ConversationAssistantSseEvent',
      oneOf: [
        { $ref: 'ConversationAssistantSseRequestState#' },
        { $ref: 'ConversationAssistantSseContextAttached#' },
        { $ref: 'ConversationAssistantSseUserTurn#' },
        { $ref: 'ConversationAssistantSseAssistantDelta#' },
        { $ref: 'ConversationAssistantSseUsage#' },
        { $ref: 'ConversationAssistantSseError#' },
        { $ref: 'ConversationAssistantSseAssistantTurn#' },
        { $ref: 'ConversationAssistantSseDone#' },
      ],
    },
  ];
}

function sseOptionalIdentityEvent(
  id: string,
  type: string,
  properties: JsonSchema,
  required: string[],
  identity: JsonSchema
): JsonSchema {
  return {
    $id: id,
    type: 'object',
    additionalProperties: false,
    properties: {
      type: { type: 'string', const: type },
      ...identity,
      ...properties,
    },
    required: ['type', ...required],
  };
}
