import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = resolve(__dirname, '..', '..');
const generatorPath = resolve(repoRoot, 'scripts', 'generate-dev-caddy.mjs');
const profileManifestPath = resolve(repoRoot, 'config', 'edge', 'dev-hibernation.json');
const generatedDirectory = resolve(repoRoot, 'config', 'edge', 'generated');

const PROFILES = ['active-pre-cutover', 'active-post-cutover', 'draining', 'hibernated'] as const;

const DRAINING_CALLBACKS = [
  '/api/code/internal/webhooks/task-complete',
  '/api/code/internal/logs',
  '/api/code/internal/turn-metrics',
  '/api/code/internal/webhooks/task-event',
  '/api/code/internal/webhooks/compliance-report',
  '/api/code/internal/code-tasks/status',
] as const;

function generateProfile(profile: (typeof PROFILES)[number]): string {
  return execFileSync(process.execPath, [generatorPath, '--profile', profile], {
    cwd: repoRoot,
    encoding: 'utf8',
  });
}

function generateMatrixFragment(): string {
  return execFileSync(process.execPath, [generatorPath, '--matrix-fragment'], {
    cwd: repoRoot,
    encoding: 'utf8',
  });
}

function countOccurrences(value: string, pattern: RegExp): number {
  return value.match(pattern)?.length ?? 0;
}

describe('DEV immutable edge profiles', () => {
  it('requires one explicit, closed-set output selector', () => {
    expect(spawnSync(process.execPath, [generatorPath], { cwd: repoRoot }).status).not.toBe(0);
    expect(
      spawnSync(process.execPath, [generatorPath, '--profile', 'active'], { cwd: repoRoot }).status
    ).not.toBe(0);
    expect(
      spawnSync(process.execPath, [generatorPath, '--profile', 'hibernated', '--matrix-fragment'], {
        cwd: repoRoot,
      }).status
    ).not.toBe(0);
  });

  it('freezes the complete profile manifest contract', () => {
    expect(JSON.parse(readFileSync(profileManifestPath, 'utf8'))).toEqual({
      draining: {
        retainedMachinePaths: DRAINING_CALLBACKS,
        statusCode: 503,
      },
      hibernated: {
        retryAfterSeconds: 300,
        statusCode: 503,
      },
      matrix: {
        accessLog: '/var/log/caddy/intexuraos-matrix-outbound-access.json',
        host: 'matrix-outbound.intexuraos.cloud',
      },
      postCutover: {
        matrixStatusCode: 410,
      },
      profiles: PROFILES,
      schemaVersion: 1,
    });
  });

  it.each(PROFILES)('generates deterministic tracked fixture for %s', (profile) => {
    const first = generateProfile(profile);
    const second = generateProfile(profile);
    const fixture = readFileSync(resolve(generatedDirectory, `${profile}.caddy`), 'utf8');

    expect(first).toBe(second);
    expect(first).toBe(fixture);
  });

  it('generates a deterministic tracked Matrix fixture', () => {
    const first = generateMatrixFragment();
    const second = generateMatrixFragment();
    const fixture = readFileSync(resolve(generatedDirectory, 'matrix-outbound.caddy'), 'utf8');

    expect(first).toBe(second);
    expect(first).toBe(fixture);
  });

  it('keeps the old Matrix upstream only in active-pre-cutover', () => {
    const outputs = new Map(PROFILES.map((profile) => [profile, generateProfile(profile)]));
    const preCutover = outputs.get('active-pre-cutover') ?? '';

    expect(preCutover).toContain('handle_path /api/matrix-outbound/* {');
    expect(preCutover).toContain('reverse_proxy 127.0.0.1:8099');
    for (const profile of PROFILES.filter((name) => name !== 'active-pre-cutover')) {
      expect(outputs.get(profile)).not.toContain('127.0.0.1:8099');
    }
  });

  it('preserves the complete pre-cutover output byte-for-byte apart from its profile label', () => {
    const normalized = generateProfile('active-pre-cutover').replace(
      /^.*\n/u,
      '# Generated by scripts/generate-dev-caddy.mjs. Do not edit on the host.\n'
    );

    expect(createHash('sha256').update(normalized).digest('hex')).toBe(
      'a1ebb596cb3a6986160733964306eb144b78c051f2a1d7b4cb7f11d711268430'
    );
  });

  it('retires the old Matrix prefix before the SPA with a non-cacheable plain-text 410', () => {
    const output = generateProfile('active-post-cutover');
    const retiredHandler = output.indexOf('handle @retiredMatrix {');
    const spaFallback = output.indexOf('root * /var/www/intexuraos-dev/current');

    expect(output).toContain('path /api/matrix-outbound /api/matrix-outbound/*');
    expect(output).toContain('header Cache-Control "no-store"');
    expect(output).toContain('header Content-Type "text/plain; charset=utf-8"');
    expect(output).toContain('respond "Gone" 410');
    expect(output).not.toContain('127.0.0.1:8099');
    expect(retiredHandler).toBeGreaterThan(-1);
    expect(spaFallback).toBeGreaterThan(retiredHandler);
  });

  it('draining exposes exactly the six callback-safe routes and no broad or static route', () => {
    const output = generateProfile('draining');
    const paths = [...output.matchAll(/^\s+path (\/api\/\S+)$/gmu)].map((match) => match[1]);

    expect(paths).toEqual(DRAINING_CALLBACKS);
    expect(countOccurrences(output, /reverse_proxy 127\.0\.0\.1:8128/gu)).toBe(
      DRAINING_CALLBACKS.length
    );
    expect(countOccurrences(output, /reverse_proxy/gu)).toBe(DRAINING_CALLBACKS.length);
    expect(output).not.toContain('handle_path');
    expect(output).not.toContain('handle_path /api/code/*');
    expect(output).not.toContain('/api/linear/webhooks');
    expect(output).not.toContain('/api/notifications/webhooks');
    expect(output).not.toContain('/api/code/webhooks/sentry');
    expect(output).not.toContain('root *');
    expect(output).not.toContain('file_server');
    expect(output).toContain('respond "Service Unavailable" 503');
  });

  it('hibernated owns DEV ingress with bounded retry and no application surface', () => {
    const output = generateProfile('hibernated');

    expect(output).toContain('dev.intexuraos.cloud:80 {');
    expect(output).toContain('format json');
    expect(output).toContain('header Cache-Control "no-store"');
    expect(output).toContain('header Retry-After "300"');
    expect(output).toContain('header Content-Type "text/plain; charset=utf-8"');
    expect(output).toContain('respond "Service Unavailable" 503');
    expect(output).not.toContain('reverse_proxy');
    expect(output).not.toContain('root *');
    expect(output).not.toContain('file_server');
    expect(output).not.toMatch(/127\.0\.0\.1:\d+/u);
  });

  it('Matrix fragment exposes only the production-owned exact prefix to port 8099', () => {
    const output = generateMatrixFragment();

    expect(output).toContain('matrix-outbound.intexuraos.cloud:80 {');
    expect(output).toContain('path /api/matrix-outbound /api/matrix-outbound/*');
    expect(countOccurrences(output, /reverse_proxy/gu)).toBe(1);
    expect(output).toContain('reverse_proxy 127.0.0.1:8099');
    expect(output).toContain('respond "Not Found" 404');
    expect(output).not.toContain('dev.intexuraos.cloud:80');
    expect(output).not.toContain('root *');
    expect(output).not.toContain('file_server');
    expect(output).not.toMatch(/127\.0\.0\.1:(?!8099\b)\d+/u);
  });
});
