#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RUNTIME_CONFIG_RENDERER="${REPO_ROOT}/scripts/render-runtime-config.mjs"
OUTPUT_FILE="${OUTPUT_FILE:-/etc/intexuraos/grafana-cloud.env}"
SECRET_PACKAGE_RENDER_DIR="${SECRET_PACKAGE_RENDER_DIR:-${HOME}/.config/intexuraos/secret-packages/dev}"
INTEXURAOS_ENVIRONMENT="${INTEXURAOS_ENVIRONMENT:-dev}"
TEMP_ENV_FILE=""

GRAFANA_CLOUD_COLLECTOR_CONFIG=(
  INTEXURAOS_GRAFANA_CLOUD_LOKI_URL
  INTEXURAOS_GRAFANA_CLOUD_LOKI_USERNAME
)

GRAFANA_CLOUD_COLLECTOR_TOKEN="INTEXURAOS_GRAFANA_CLOUD_LOKI_TOKEN"

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

cleanup() {
  if [[ -n "${TEMP_ENV_FILE}" ]]; then
    rm -f "${TEMP_ENV_FILE}"
  fi
}

dotenv_escape() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  printf '"%s"' "${value}"
}

write_env_line() {
  local output_path="$1"
  local key="$2"
  local value="$3"

  printf '%s=%s\n' "${key}" "$(dotenv_escape "${value}")" >> "${output_path}"
}

read_rendered_token() {
  local rendered_env_file="$1"
  local token=""

  if [[ ! -f "${rendered_env_file}" ]]; then
    fail "Rendered DEV package environment is unavailable"
  fi
  if [[ -L "${rendered_env_file}" ]]; then
    fail "Rendered DEV package environment must not be a symlink"
  fi

  if ! token="$(
    RENDERED_ENV_FILE="${rendered_env_file}" \
      GRAFANA_TOKEN_NAME="${GRAFANA_CLOUD_COLLECTOR_TOKEN}" \
      node <<'NODE'
const { readFileSync } = require('node:fs');
const { parse } = require('dotenv');

const path = process.env.RENDERED_ENV_FILE;
const tokenName = process.env.GRAFANA_TOKEN_NAME;
if (!path || !tokenName) process.exit(2);
const parsed = parse(readFileSync(path, 'utf8'));
const token = parsed[tokenName];
if (typeof token !== 'string' || token.length === 0) process.exit(3);
process.stdout.write(token);
NODE
  )"
  then
    fail "Rendered DEV package is missing ${GRAFANA_CLOUD_COLLECTOR_TOKEN}"
  fi

  printf '%s' "${token}"
}

publish_output() {
  chmod 600 "${TEMP_ENV_FILE}"
  if [[ "$(id -u)" -eq 0 ]]; then
    chown root:root "${TEMP_ENV_FILE}"
  fi
  mv -f "${TEMP_ENV_FILE}" "${OUTPUT_FILE}"
  TEMP_ENV_FILE=""
}

main() {
  trap cleanup EXIT

  if [[ "${INTEXURAOS_ENVIRONMENT}" != "dev" ]]; then
    fail "load-grafana-cloud-env.sh is for home-dev; use scripts/hetzner/load-secrets.sh for prod"
  fi

  command -v node >/dev/null 2>&1 || fail "node is required for runtime configuration"
  local rendered_env_file="${SECRET_PACKAGE_RENDER_DIR}/current/environment.env"
  local token=""
  token="$(read_rendered_token "${rendered_env_file}")"

  umask 077
  install -d -m 755 "$(dirname "${OUTPUT_FILE}")"
  TEMP_ENV_FILE="$(mktemp "${OUTPUT_FILE}.staging.XXXXXX")"

  cat > "${TEMP_ENV_FILE}" <<HEADER
# Generated by scripts/observability/load-grafana-cloud-env.sh.
# Do not edit by hand. URL/username are tracked; token comes from the rendered DEV package.
HEADER
  write_env_line "${TEMP_ENV_FILE}" "INTEXURAOS_ENVIRONMENT" "dev"

  local config_args=()
  local config_name=""
  for config_name in "${GRAFANA_CLOUD_COLLECTOR_CONFIG[@]}"; do
    config_args+=(--key "${config_name}")
  done
  if ! node "${RUNTIME_CONFIG_RENDERER}" \
    --environment dev \
    --format dotenv \
    "${config_args[@]}" >> "${TEMP_ENV_FILE}"
  then
    fail "Unable to render tracked Grafana Cloud configuration"
  fi

  write_env_line "${TEMP_ENV_FILE}" "${GRAFANA_CLOUD_COLLECTOR_TOKEN}" "${token}"
  publish_output
  printf 'Wrote Grafana Cloud collector environment to %s\n' "${OUTPUT_FILE}"
}

main "$@"
